### ISSUE TITLE
Detailansicht der Einrichtungen: Farben anpassen und Symbole nutzen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#10]
Bitte "unsere" Farben nutzen und je Themenbereich mit unterschiedlichen Symbolen arbeiten, d.h. z.B. Kindertageseinrichtungen als Punkte, allgemeinbildende Schulen als Quadrate, Einrichtungen der Erwachsenenbildung als Rauten, Berufsfachschulen als Sterne.

**Comment by rockgobo** [comment]
- [x] Bilo farben verwenden 
- [x] Symbole für unterschiedliche Schularten verwenden
