### ISSUE TITLE
Schulde: Sekundarstufe - Kennzahl "Anteil öffentlicher Freier Waldorfschulen" löschen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#100]

**Comment by rockgobo** [comment]
Falls du "Öffentliche Freie Waldorfschulen - Anteil" meinst, das habe ich jetzt gelöscht :-) Aber keine Sorge ich habe das so eingebaut, dass die Daten nicht gelöscht werden, sondern nur als gelöscht markiert. Ich kann das auch mal im Adminbereich einbauen.

**Comment by IngridStoehr** [comment]
Das ist eine super Idee, denn – Warnung – es kommen jetzt noch ein paar so neue Fälle, wo Kennzahlen doch raussollen und neue rein und die Reihenfolge ein bisschen geändert werden sollte… Wollen wir uns heute mal kurz treffen?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Januar 2017 17:00
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Schulde: Sekundarstufe - Kennzahl "Anteil öffentlicher Freier Waldorfschulen" löschen (#100)


Falls du "Öffentliche Freie Waldorfschulen - Anteil" meinst, das habe ich jetzt gelöscht :-) Aber keine Sorge ich habe das so eingebaut, dass die Daten nicht gelöscht werden, sondern nur als gelöscht markiert. Ich kann das auch mal im Adminbereich einbauen.
