### ISSUE TITLE
Regionenansicht: Strukturelle Rahmendaten - Reihenfolge der Kennzahl

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#103]
Hier stimmt die Reihenfolge noch nicht, die zuletzt hinzugekommenen Kennzahlen stehen an erster Stelle.

**Comment by rockgobo** [comment]
Ich glaube das hat sich mit der Zuordnung zu den Überbegriffen erledigt.

**Comment by IngridStoehr** [comment]
In der Regionenansicht stimmt es leider immer noch nicht - SGBII-Quote steht immer noch an erster Stelle, wenn man die Strukturellen Rahmendaten aufklappt

**Comment by rockgobo** [comment]
Besser so?

**Comment by IngridStoehr** [comment]
Jetzt fängt es bei mir mit Arbeitslosenquote Männer an… - Ließe sich die Reihenfolge aus dem ausklappbaren Menü der Themenansicht übernehmen?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 25. Januar 2017 10:29
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Regionenansicht: Strukturelle Rahmendaten - Reihenfolge der Kennzahl (#103)


Besser so?
