### ISSUE TITLE
Regionenansicht: Liniendiagramme

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#106]
Hier müssten wir uns nochmal zusammensetzen und überlegen...
u.a. folgende Punkte
- [x] Start nicht immer direkt auf der y-Achse, sondern ein "Stückchen" danach
- [x] letztes berichetes Jahr (Jahreszahl) sollte auf der y-Achse sichtbar sein
- [x] offen: Lösung der Darstellung von absoluten Zahlen - Kreisgebiet vs. OFR-Durchschnitt

**Comment by IngridStoehr** [comment]
- [x] Maximum der x-Achse an maximale Werte anpassen (mit Luft nach oben)

**Comment by IngridStoehr** [comment]
Sorry... als ich mir das jetzt in der Regionenansicht angeguckt habe, ist mir aufgefallen, dass ich wohl bei der Aufgabe "Maximum der x-Achse an maximale Werte anpassen (mit Luft nach oben)" die Achsen vertauscht hatte, gemeint war die y-Achse, denn sonnst sind die Liniendiagramme ja nichtssagend. Wie gesagt: SORRY!

D.h. die x-Achse sollte gerade bei den Anteilen bis 100% gehen bzw. bei Werten von <10% auf Kreisebene und OFR-Ebene bis 50%.
Bei den absoluten Zahlen ist es m.E. i.O., wenn der OFR-Wert die Richtschnur bildet. Danke!

**Comment by IngridStoehr** [comment]
Und hier würde ich, nachdem ich nun "gesehen" habe, auch nochmal ändern (meine Vorstellungskraft ist leider nicht ausreichend und die Schleifen tun mir leid!), denn tatsächlich sieht man nicht mehr so viel, wenn die y-Achse bei den Prozentzahlen bis 50 % geht und die Werte irgendwo bei 0 bis 10 rumkrebsen... 
Wäre bei Werten <10 eine y-Achse bis 10 oder 20 % möglich? (Was sieht besser aus, um noch eine Schleife zu verhindern...)?

**Comment by rockgobo** [comment]
Ich werde folgendes machen 
- max < 40 => 50
- max < 10 => 20

**Comment by IngridStoehr** [comment]
Danke, das sieht doch gut aus!

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 16. Februar 2017 09:01
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; State change <state_change@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Regionenansicht: Liniendiagramme (#106)


Ich werde folgendes machen

  *   max < 40 => 50
  *   max < 10 => 20
