### ISSUE TITLE
Berufliche Bildung: Regionenansicht "no data available" falsch

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#112]
In der Regionenansicht wird in Kreisen, die keine beruflichen Schulen haben bei den Kennzahlen zum SBS "no data available" angezeigt, weil die Werte 0 sind (in der Themenansicht wird hier jeweils 0 in Karte bei Mouseover, 0 % in Ringdiagramm und "." in der Tabelle angezeigt - hier wäre eine einheitliche Darstellung wünschenswert), wird sich das in der REgionenansicht ändern, sobald die OFR-Werte vorliegen?

**Comment by rockgobo** [comment]
Dann sind eigentlich keine Werte vorhanden, ich habe bei Ring und Karte
noch ein konzeptionelles Problem, das ich nicht auf die schnelle in die
missing Logik überführen kann.

IngridStoehr <notifications@github.com> schrieb am Do., 19. Jan. 2017,
09:11:
