### ISSUE TITLE
Ringdiagram bei Datensätzen mit negativen Zahlen nicht anzeigen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#116]
Darstellung in der Diagrammform nicht korrekt (einfarbig, durcheinander) - in Tabelle und Karte schon

**Comment by IngridStoehr** [comment]
Betrifft auch Wanderungssaldo deutsche Bevölkerung - hier auch jüngere Jahre

**Comment by IngridStoehr** [comment]
Liegt an negativen Werten - hier keine anzeige von Ringdiagrammen

**Comment by rockgobo** [comment]
Es wird die Anzeige des Diagramm unterbunden, falls die Ansicht noch nicht geöffnet ist. Ansonsten kommt ein Hinweis mit der Bitte eine andere Visualisierungsform zu wählen.
