### ISSUE TITLE
Themenbereich Studium: neue Hierarchie

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#117]
Die Kennzahlen zum Bereich Studium bleiben gleich, das ist die gute Nachricht. Sie müssten bitte in eine neue Reihenfolge gebracht werden, das ist die schlechte Nachricht.
Die Übersicht zur neuen Reihenfolge findest Du hier: Neu im Vergleich zu Alt mit kleinen Hinweisen zu den Veränderungen. Die neuen Namen sind bereits umgesetzt. Nur die ZWISCHENÜBERSCHRIFTEN müsstest Du noch anpassen, eine Zwischenüberschrift (Hochschulzugangsberechtigung) fällt weg.
[Hierarchie Studium.xlsx](https://github.com/rockgobo/biloatlas/files/731791/Hierarchie.Studium.xlsx)

**Comment by IngridStoehr** [comment]
"Sort order" und Kennzahlen löschen funktioniert wunderbar, ich habe das u.a. bei Frühki schon umgesetzt und bei Studium nun die Vorarbeit geleistet, der Rest betrifft die Zwischenüberschriften, die ich nicht bearbeiten kann. Im Einzelnen wäre das:
1, Zwischenüberschrift "Hochschulzugangsberechtigung" löschen und die Kennzahl darunter der Zwischenüberschrift "Wahl des Studienortes" zuweisen (sort order passt schon)
2. Zwischenüberschrift "Wahl des Studienortes" inkl. Kennzahlen bitte an das Ende
3. Zwischenüberschrift "HochschulabsolventInnen" bitte in "Hochschulabsolventinnen und Hochschulabsolventen" ändern
4. Zwischenüberschrift "StudienanfängerInnen" bitte in "Studienanfängerinnen und Studienanfänger" ändern
5. Zwischenüberschrift "Studierende" bitte in "Studierende nach Fachbereichen" ändern und bitte den Block inkl. Kennzahlen VOR "Studienanfängerinnen und Studienanfänger" 

Die Gesamtübersicht hättest Du auch nochmals im Excel oben.

**Comment by rockgobo** [comment]
- [x] 1, Zwischenüberschrift "Hochschulzugangsberechtigung" löschen und die Kennzahl darunter der Zwischenüberschrift "Wahl des Studienortes" zuweisen (sort order passt schon)
- [x] 2. Zwischenüberschrift "Wahl des Studienortes" inkl. Kennzahlen bitte an das Ende
- [x] 3. Zwischenüberschrift "HochschulabsolventInnen" bitte in "Hochschulabsolventinnen und Hochschulabsolventen" ändern
- [x] 4. Zwischenüberschrift "StudienanfängerInnen" bitte in "Studienanfängerinnen und Studienanfänger" ändern
- [x] 5. Zwischenüberschrift "Studierende" bitte in "Studierende nach Fachbereichen" ändern und bitte den Block inkl. Kennzahlen VOR "Studienanfängerinnen und Studienanfänger"
