### ISSUE TITLE
Kennzahlen löschen - Kommt die Möglichkeit noch? Ansonsten bitte...

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#119]
unter Erwachsenenbildung folgende Kennzahlen löschen:
Teilnehmende im PB Gesellschaft - Anzahl
Teilnehmende im PB Kultur - Anzahl
Teilnehmende im PB Gesundheit - Anzahl
Teilnehmende im PB Sprachen - Anzahl
Teilnehmende im PB Beruf - Anzahl
Teilnehmende im PB Grundbildung - Anzahl

**Comment by rockgobo** [comment]
Kennzahlen wurde mithilfe der neuen Oberfläche gelöscht. In der Übersicht und in der Bearbeitungsmaske kann man nun die Kennzahlen auch löschen.

**Comment by IngridStoehr** [comment]
Super! Hab ich auch schon ausprobiert! Und das „Bearbeite Daten“ ist nun auch schon nutzbar?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Montag, 30. Januar 2017 14:51
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Kennzahlen löschen - Kommt die Möglichkeit noch? Ansonsten bitte... (#119)


Kennzahlen wurde mithilfe der neuen Oberfläche gelöscht. In der Übersicht und in der Bearbeitungsmaske kann man nun die Kennzahlen auch löschen.

**Comment by rockgobo** [comment]
Die Daten lassen sich noch nicht bearbeiten.

**Comment by IngridStoehr** [comment]
Und die Reihenfolge über „Sort order“?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 09:59
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Kennzahlen löschen - Kommt die Möglichkeit noch? Ansonsten bitte... (#119)


Die Daten lassen sich noch nicht bearbeiten.

**Comment by rockgobo** [comment]
Die SortOrder kannst du über die Bearbeitung der Kennzahlen setzen
