### ISSUE TITLE
favicon fehlt

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#120]
Jemand könnte noch ein schickes Favicon bauen. Hat gerade mein Browser verkündet. Vielleicht so eine kleine rote Lupe.

**Comment by IngridStoehr** [comment]
Ich leite Dir das von Johannes für die BiLO-Seiten entwickelte favicon per mail weiter, da ich beim Versuch des Hochladens hier die Fehlermeldung bekomme, dass der Typ nicht unterstützt werde...
