### ISSUE TITLE
Duplikate in den Datensätzen 

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#124]
Ich habe leider gerade auch ein echtes Problem endeckt, und zwar sind irgendwie Duplikate ins System gekommen. Ungefähr 500 Datenpunkt gibt es doppelt mit unterschiedlichen Werten... das ist nicht gut, gar nicht gut. 

Viele davon werden durch das neue Laden der Beruflichen Bildung rausfliegen, aber den Rest müssen wir uns nochmal anschauen.

**Comment by IngridStoehr** [comment]
o.k., morgen? Heute ginge nur um halb 12…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 10:01
An: rockgobo/biloatlas
Cc: Subscribed
Betreff: [rockgobo/biloatlas] Duplikate in den Datensätzen (#124)


Ich habe leider gerade auch ein echtes Problem endeckt, und zwar sind irgendwie Duplikate ins System gekommen. Ungefähr 500 Datenpunkt gibt es doppelt mit unterschiedlichen Werten... das ist nicht gut, gar nicht gut.

Viele davon werden durch das neue Laden der Beruflichen Bildung rausfliegen, aber den Rest müssen wir uns nochmal anschauen.

**Comment by rockgobo** [comment]
Nicht erschrecken, der Code ist für mich:
`/****** Find Duplicates  ******/
SELECT region_id, layer_id,Year,count(*) as values_count
	INTO atlas.duplicates_keys
  FROM [Bilo].[atlas].[Values]
  group BY region_id, layer_id,Year
  having count(*) > 1	
  
/****** SELECT Duplicates into new Table  ******/
SELECT DISTINCT atlas.[values].*
INTO atlas.duplicates
FROM atlas.[values], atlas.duplicates_keys
WHERE atlas.[values].Layer_id = atlas.duplicates_keys.Layer_id
AND atlas.[values].Region_id = atlas.duplicates_keys.Region_id	
AND atlas.[values].[year] = atlas.duplicates_keys.[year]`

**Comment by rockgobo** [comment]
Z:\00_Austausch\BiLO\BiLO-Atlas\Duplikate

**Comment by IngridStoehr** [comment]
Es stimmt keiner der Werte (?)… ich lege heute (wenn ich es schaffe) oder morgen eine neue Excel mit den neuen Namen ab (und es kommen auch noch neue Kennzahlen dazu – jeweils die weiblichen Anteile) zu Schulbildung: Sekundarstufe – Zwischenüberschrift: Absolventinnen und Absolventen. Ich hoffe, das ist o.k.



Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 1. Februar 2017 09:59
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Duplikate in den Datensätzen (#124)


Z:\00_Austausch\BiLO\BiLO-Atlas\Duplikate

**Comment by IngridStoehr** [comment]
Die Excel liegt im Austauschordner und hier:
[Daten-Sek_Onl_GS-Sek_weibl_+Absolv berichtigt_170201.xlsx](https://github.com/rockgobo/biloatlas/files/744627/Daten-Sek_Onl_GS-Sek_weibl_.Absolv.berichtigt_170201.xlsx)
Es gibt zwei Tabellenblätter, das erste enthält die neuen Kennzahlen mit den weiblichen Anteilen, hier sind auch welche für Primarstufe und Sekundarstufe (nach Schultypen) drin.
Das zweite Tabellenblatt beinhaltet die Kennzahlen, deren Werte aktuell falsch im webAtlas sind, sie betreffen ausgewählte Kennzahlen der Zwischenüberschrift "Absolventinnen und Absolventen".

Ich habe die alte Excel in history verschoben, die nicht mehr relevant ist. 

Hast Du noch Fragen dazu?

**Comment by rockgobo** [comment]
Ich werfe dann die aktuellen Duplikate weg und lade die neuen Daten. Dann kann ich dazwischen nämlich kurz die Primärschlüssel in die Tabelle einfügen, dann kommt es nie mehr zu Duplikaten.

**Comment by rockgobo** [comment]
#133 Den Teil mit dem Laden der Datei in einen neuen Issue verschoben.
