### ISSUE TITLE
Keine Angabe und Wert "0"

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#126]
Das bleibt... Hier zunächst einmal in Prosa, wie es sein sollte... Es werden verschiedene Fälle unterschieden:

Fall a) Bsp. Hochschulen
--> Es gibt Kreise mit Hochschulen und Kreise ohne Hochschulen. Hier ist es richtig, wenn 0 Hochschulen in der Karte / Tabelle angezeigt werden.

Fall b) Bsp. Erstsemester - Anteil: Sprache, Kultur
--> Es gibt 2 Kreisgebiete, die hier Werte haben. In drei Kreisen könnte es theoretisch welche geben, da es Hochschulen gibt, sie haben aber keine Studis mit Sprache und Kultur, daher ist hier 0% richtig, in den restlichen Kreisen kann es gar keine geben, da es keine Hochschulen gibt, daher hier "Keine Angabe" 

Im Allgemeinen wäre der Wunschzustand:

**Bitte den Wert "0" anzeigen**
- bei der Anzahl der EINRICHTUNGEN (alle Themenbereiche), wenn es keine gibt
- bei allen anderen Kennzahlen, wenn es theoretisch höhere Werte geben könnte, Bsp. Studium (s.o. - Sprache und Kultur)

**Bitte "Keine Angabe" anzeigen**
- bei allen Kennzahlen der einzelnen Themenbereiche, wenn die Anzahl der Einrichtung gleich 0
- bei allen Kennzahlen, die etwa aus Datenschutzgründen keine Daten ausweisen dürfen (s.u.)

Ist in der Legende bei "Keine Angabe" ein Infobutton möglich, in dem erläutert werden könnte, was "Keine Angabe" alles heißt?

Im Speziellen wäre die Vorlage für die einzelnen Themenbereiche wie folgt:
- [x] FRÜHKINDLICHE BILDUNG
--> betrifft Kindertagespflege Ganztagsbetreuung --> Wert "0" (wie bisher)

- [x] SCHULBILDUNG: PRIMARSTUFE
--> keine Fälle

- [x] SCHULBILDUNG: SEKUNDARSTUFE
- [x] -> Gymnasien: Anzahl Gymnasien 
      --> im Landkreis Bamberg 0, d.h. für alle folgenden Kennzahlen zu Gymnasium bitte bei Landkreis     Bamberg "Keine Angabe"
- [x] --> Freie Waldofrschulen: Anzahl Freie Waldorfschulen 
- [x]         --> diese gibt es nur in der Stadt Hof, Stadt Coburg und im Landkreis Kulmbach, bei allen anderen 0 Schulen, d.h. für alle folgenden Kennzahlen zu Waldorfschulen bitte bei allen Kreisen, die keine Einrichtung haben, ein "Keine Angabe" anzeigen;

- [x] BERUFLICHE BILDUNG
- [x] --> Duale Ausbildung (DA) - Anzahl Berufsschulen 
       --> im Landkreis Bamberg und im Landkreis Coburg 0, d.h. für alle folgenden Kennzahlen zu DA bitte bei diesen beiden Landkreisen ein "Keine Angabe", bei allen anderen ggf. den Wert 0 anzeigen

- [x] --> Schulberufssystem (SBS) - Anzahl Berufsfachschulen & Anzahl Berufsfachschulen des Gesundheitswesens 
- [x]        --> im Landkreis Bamberg & Landkreis Coburg 0, im Landkreis Kulmbach zwar 4 Berufsfachschulen des Gesundheitswesens, aber alle privat und daher aus Datenschutzgründen keine Datenanzeige, d. h. für alle folgenden Kennzahlen zu SBS bitte bei diesen drei Landkreisen ein "Keine Angabe" anzeigen

- [x] --> Übergangssystem (ÜS) --> im Landkreis Bamberg und im Landkreis Coburg gibt es keine Einrichtungen des beruflichen Schulsystems, d. h. für alle folgenden Kennzahlen zu SBS bitte bei diesen beiden Landkreisen ein "Keine Angabe" anzeigen, bei allen anderen ggf. den Wert 0 anzeigen

- [x] --> alle IHK-Kennzahlen --> bitte hier für den Landkreis Coburg "Keine Angabe" anzeigen

- [x] HOCHSCHULE
- [x] --> Anzahl Hochschule 
- [x]        --> 4 Städte & Landkreis Hof haben eine Hochschule, bei anderen Kreisgebieten gibt es keine, d. h. für alle Kennzahlen bei diesen anderen Kreisgebieten ein "Keine Angabe" anzeigen (Ausnahme: 4 Kennzahlen unter "Wahl des Studienortes", hier liegen Werte für alle Kreise vor)

- [x] ERWACHSENENBILDUNG:VHS
- [x] --> Landkreis Coburg: wie besprochen hier "Keine Angabe" anzeigen, da haben wir ja auch noch den Hinweis....

Ich hoffe das klappt so, ohne dass wir die mehr als 5000 Datenzeilen durchgehen müssen... Danke Dir!

**Comment by rockgobo** [comment]
Also ich mache jetzt folgendes ich gehe deine Beschriebungen durch und lösche bestimmte Zeilen aus den Daten wieder raus oder füge Zeilen mit 0 ein. Das hat folgenden Hintergrund:
- Jede Zahl die in den Zeilen zu (Thema, Region und Jahr) einen Wert hat wird angezeigt, steht dort 0 wird eben auch 0 angezeigt
- Ist ein Tupel aus (Thema, Region, Jahr und Wert) gar nicht in den Daten wird in Atlas "Keine Angabe" verwendet

Nach dieser Logik muss ich nun anhand deiner Beschreibungen (wie in Mathe bei den Textaufgaben) mir den passenden Filter überlegen und dann eine der beiden Regeln anwenden. Kann sein, dass ich bei der einen oder anderen Stell noch nachfragen habe.

**Comment by rockgobo** [comment]
Ich habe jetzt die "Keine Angaben" nach der Beschreibung eingepflegt, die 0er müssten eigentlich passen, da ich glaube ich bis auf Studiumsdaten meistens eine 0 erzeugt habe.... Falls noch 0er fehlen einfach noch ein Issue aufmachen "0er einpflegen" und beschreiben wo echte nullen hingehören.

**Comment by IngridStoehr** [comment]
Leider stimmt es noch nicht ganz. 
**Bei Schulbildung: Sekundarstufe**
- [x] Kennzahl "Gymnasien - Anzahl" --> hier müsste der Landkreis Bamberg in der Karte weiß sein und in der Tabelle "0" und kein Missing angezeigt werden
--> Die folgenden Kennzahlen zu Gymnasien, die Anteile etc. beschreiben, stimmen!
- [x] Kennzahl "Freie Waldorfschulen - Anzahl" --> hier gibt es nur drei Kreisgebiete mit Schulen, alle anderen müssten weiß in der Karte sein und eine 0 in der Tabelle anzeigen, bisher ist das nur bei der Stadt Bayreuth so, alle anderen sind grau und haben ein Missing
--> bei den folgenden Kennzahlen zu Waldorfschulen bleibt Bayreuth weiß und alle anderen grau, hier wäre richtig, wenn auch Bayreuth grau würde und ein Missing bekäme;

**Berufliche Bildung**
- Kennzahlen "Berufsschulen - Anzahl" und "Berufsfachschulen - Anzahl" stimmen
- [x] Kennzahl "Berufsfachschulen des Gesundheitswesens - Anzahl", hier ist in der Kartenansicht Bayreuth Stadt 0 und weiß (richtig), Bamberg Landkreis und Coburg Landkreis sind noch grau und haben ein Missing in der Tabelle, diese müssten auch noch in "weiß" und "0" geändert werden;
--> die folgenden Kennzahlen stimmen

**Studium**
Hier stimmt die Kennzahl "Hochschulen - Anzahl"
- [x] --> allerdings wird bei den folgenden Kennzahlen nicht mehr unterschieden zwischen "0" (theoretisch wären Werte möglich) und "Missing" (es gibt gar keine Hochschule, also kann es auch keine Studierenden in Kunst geben)

**Erwachsenenbildung**
- [x] Bitte hier bei Landkreis Coburg bei allen Kennzahlen "Keine Angabe" zeigen, wir haben nun ja den blauen Kasten....

**Comment by IngridStoehr** [comment]
und noch eine Ergänzung:
**Schulbildung: Sekundarstufe**
--> alle Kennzaheln zu Absolventinnen und Absolventen mit allgemeiner Hochschulreife - hier müsste Landkreis Bamberg grau sein, da es dort kein Gymnasium gibt und so auch keine Absolventen geben kann...

**Comment by rockgobo** [comment]
zu der Ergänzung:
Schulbildung: Sekundarstufe
Meinst du die Kennzahlen zu "SuS mit allgemeiner Hochschulreife - xyz"?

**Comment by IngridStoehr** [comment]
Ja, genau, die meine ich.
SuS mit allgemeiner Hochschulreife - Anzahl
SuS mit allgemeiner Hochschulreife - Anteil
SuS mit allgemeiner Hochschulreife - Anteil männlich
SuS mit allgemeiner Hochschulreife - Anteil weiblich
SuS mit allgemeiner Hochschulreife - Anteil ausländisch

**Comment by IngridStoehr** [comment]
Leider erscheinen die zuletzt genannten Kennzahlen nicht mehr grau. Bitte wieder grau färben und Missing anzeigen, wenn Landkreis Bamberg:
SuS mit allgemeiner Hochschulreife - Anzahl
SuS mit allgemeiner Hochschulreife - Anteil
SuS mit allgemeiner Hochschulreife - Anteil männlich
SuS mit allgemeiner Hochschulreife - Anteil weiblich
SuS mit allgemeiner Hochschulreife - Anteil ausländisch
