### ISSUE TITLE
Facettensystem für die Kennzahlen

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#127]
Viele Kennzahlen entstehen ja dadurch, dass noch mal eine weitere Ebene dieser Kennzahl betrachtet wird (Männlich/weiblich) oder (Fachbereich Sport, Mathe, Physik, ...)
Um übersichtlich zu bleiben sollte man diese Facetten einer Kennzahl als solche auf eine eigene Abstraktionsebene ziehen.

**Comment by IngridStoehr** [comment]
Heißt das vereinfacht, dass sie im ausklappbaren Menü etwas „eingerückt“ sind?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Freitag, 3. Februar 2017 15:48
An: rockgobo/biloatlas
Cc: Subscribed
Betreff: [rockgobo/biloatlas] Facettensystem für die Kennzahlen (#127)


Viele Kennzahlen entstehen ja dadurch, dass noch mal eine weitere Ebene dieser Kennzahl betrachtet wird (Männlich/weiblich) oder (Fachbereich Sport, Mathe, Physik, ...)
Um übersichtlich zu bleiben sollte man diese Facetten einer Kennzahl als solche auf eine eigene Abstraktionsebene ziehen.

**Comment by rockgobo** [comment]
Ne ich würde die komplett aus dem Menü rausziehen. Aber der Umbau kostet einiges an Kraft und Zeit. Man hätte dann eine Art drittes Pulldownmenü, oder man könnte sich auch abgefahrerene Auswahlmöglichkeiten, wie beispielsweise kleine Icons (männlich / weiblich) oder anderes vorstellen.

**Comment by IngridStoehr** [comment]
Christian, ne, das muss dann nicht sein! Lieber Kraft und Zeit für all die Anmerkungen aufsparen, die von den noch ausstehenden Abstimmungen kommen werden (Michaela, Öffentlichkeitsarbeit, Jutta) - ich finde, das sieht trotzdem gut aus!!!
________________________________
Von: rockgobo [notifications@github.com]
Gesendet: Montag, 6. Februar 2017 16:41
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Facettensystem für die Kennzahlen (#127)


Ne ich würde die komplett aus dem Menü rausziehen. Aber der Umbau kostet einiges an Kraft und Zeit. Man hätte dann eine Art drittes Pulldownmenü, oder man könnte sich auch abgefahrerene Auswahlmöglichkeiten, wie beispielsweise kleine Icons (männlich / weiblich) oder anderes vorstellen.
