### ISSUE TITLE
Reihenfolge Kennzahlen: Bitte nach Zahlen ordnen 

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#128]
Wir haben in Primar- und Sekundarstufe nach unserer gewünschten Reihenfolge über sort order die Zahlen angepasst, allerdings können wir so die Kennzahlen nicht von einer zur anderen Zwischenüberschrift schieben, obgleich die sort order passen würde...
Z.B. Stehen aktuell die "Lehrkräfte an Grundschulen - Anteil weiblich" mit der sort order 110 unter der Zwischenüberschrift Gymnasien mit der sort order 150... 
Das betrifft mehrere Kennzahlen...

**Comment by rockgobo** [comment]
Die Zuordnung zu den Vaterknoten wurden entsprechend der Sortierreihenfolge angepasst.

**Comment by IngridStoehr** [comment]
Leider hat das nicht ganz funktioniert (ich habe auch mein Cache gelöscht, um zu verhindern, dass es daran liegen könnte…):
Folgende zwei Kennzahlen
•  SuS an Grundschulen - Anteil weiblich
•  Lehrkräfte an Grundschulen - Anteil weiblich
Sind immer noch unter Schulbildung: Sekundarstufe – Absolventinnen und Absolventen …
Und müssten aber eigentlich unter Schulbildung: Primarstufe sein.



Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 14. Februar 2017 15:27
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Reihenfolge Kennzahlen: Bitte nach Zahlen ordnen (#128)


Die Zuordnung zu den Vaterknoten wurden entsprechend der Sortierreihenfolge angepasst.

**Comment by IngridStoehr** [comment]
Leider sind die beiden obengenannten Kennzahlen
• SuS an Grundschulen - Anteil weiblich 
• Lehrkräfte an Grundschulen - Anteil weiblich
immer noch in der Sekundarstufe unter den Absolventinnen und Absolventen...

**Comment by IngridStoehr** [comment]
Mir ist gerade aufgefallen, dass das letztes Mal, als ich bei Dir unten war, offensichtlich doch nicht geklappt hat. Die beiden Kennzahlen zur Grundschule sind immer noch unter Sedundarstufe...
