### ISSUE TITLE
Kennzahlen Zuzüge über Kreisgrenzen und Fortzüge über Kreisgrenzen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#130]
Hier sind auf Kreisebene im Rahmen der Aktualisierung die Zahlenwerte für 2005 bis 2013 verloren gegangen. Sollen wir diese nochmals aufbereiten? 
[Sie waren ursprünglich hier drin, aber noch von "früher", also überhaupt nicht an den jetzigen "Standard" angepasst. 
Z:\00_Austausch\BiLO\BiLO-Atlas\1 - Strukturelle Rahmendaten_online\03_Wanderungsbewegungen ]

**Comment by IngridStoehr** [comment]
Die zugehörigen Daten sind hier:
[Kennzahlen_Struktur_Zuzüge Fortzüge_170213.xlsx](https://github.com/rockgobo/biloatlas/files/770694/Kennzahlen_Struktur_Zuzuge.Fortzuge_170213.xlsx)
... und liegen auch im Austauschordner.

**Comment by rockgobo** [comment]
geladen
