### ISSUE TITLE
Einheit: Einzahl bei Anzahl 1

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#132]

**Comment by rockgobo** [comment]
Neuen Filter für die Einheiten eingebaut, die bei dem Wert 1 den Singular übernehmen. Die Werte sind bisher direkt im Filter hinterlegt. 

- units['Personen'] = 'Person  '
- units['Hochschulen'] = 'Hochschule '
- units['Schulen'] = 'Schule'
- units['Jahre'] = 'Jahr'
