### ISSUE TITLE
Daten-Sek_Onl_GS-Sek_weibl_+Absolv berichtigt_170201.xlsx laden

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#133]
Die Excel liegt im Austauschordner und hier:
Daten-Sek_Onl_GS-Sek_weibl_+Absolv berichtigt_170201.xlsx
Es gibt zwei Tabellenblätter, das erste enthält die neuen Kennzahlen mit den weiblichen Anteilen, hier sind auch welche für Primarstufe und Sekundarstufe (nach Schultypen) drin.
Das zweite Tabellenblatt beinhaltet die Kennzahlen, deren Werte aktuell falsch im webAtlas sind, sie betreffen ausgewählte Kennzahlen der Zwischenüberschrift "Absolventinnen und Absolventen".

Ich habe die alte Excel in history verschoben, die nicht mehr relevant ist.

Hast Du noch Fragen dazu?

**Comment by IngridStoehr** [comment]
[Bis jetzt nicht.]
