### ISSUE TITLE
Lösung der Darstellung von absoluten Zahlen - Kreisgebiet vs. OFR-Durchschnitt

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#134]
split from #106

**Comment by rockgobo** [comment]
Was genau ist eigentlich das Problem?

**Comment by IngridStoehr** [comment]
Das Problem wäre, dass bei absoluten Werten die Unterschiede zwischen ganz Oberfranken und einem Kreis sehr groß sind und die Darstellung im Liniendiagramm (Darstellungsart) ggf. schwierig. Ich würde dieses aber nun zurückstellen und abwarten, ob sich nochmals jemand beschwert.
