### ISSUE TITLE
Alle Kennzahlen zu Absolventinnen und Absolventen: Jahreszahlen auf Kreisebene stimmen nicht 

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#135]
Ausnahme bilden die neu hochgeladenen - d.h. weiblichen Anteile + OFR-Werte, hier ist alles richtig.
Bei den anderen muss das erste berichtete Jahr 2005 statt 2004 sein und das letzte berichtete Jahr 2015 statt 2014 (wir hatten das mal - ist schon lange her, mit dem +1 Jahr hochrechnen). Ginge das immer noch "automatisiert"?

Ausserdem fehlen bei manchen Werten die Kreisebene und die OFR ist eine durchgezogene Linie , obgleich sie gepunktet sein müsste... das sind folgende:

- SuS ohne Abschluss - Anteil männlich  (eheln Kreis-Werte, OFR durchgezogen)
- SuS mit Abschluss der Haupt-/Mittelschule - Anteil männlich (feheln Kreis-Werte, OFR durchgezogen)
- SuS mit mittlerem Schulabschluss - Anzahl (fehlen Kreis-Werte, OFR durchgezogen)
- SuS mit allgemeiner Hochschulreife - Anzahl (feheln Kreis-Werte, OFR durchgezogen)
--> die WErte zu diesen 4 Kennzaheln waren mit in der letzten Excel in dem Tabellenblatt "Berichtigte Kennzahlen "Absolv" 
[Daten-Sek_Onl_GS-Sek_weibl_+Absolv berichtigt_170201.xlsx](https://github.com/rockgobo/biloatlas/files/773360/Daten-Sek_Onl_GS-Sek_weibl_.Absolv.berichtigt_170201.xlsx)

**Comment by rockgobo** [comment]
Die Prüfung, ob Durchgezogene Linie oder nicht gibt es seither nur bei den Regionendaten. Wird es die Regionendaten noch geben oder soll ich auch die Oberfrankendaten überprüfen?

**Comment by rockgobo** [comment]
Ok zu schnell geschrieben, die Daten scheinen in dieser Datei zu liegen.

**Comment by rockgobo** [comment]
Ich kann das irgendwie nicht automatisiert machen, da es für 2005 schon Werte für die Beschriebenen 2004er Daten gibt, ein überschreiben mit den 2004ern Daten ist wohl nicht genau das was man erwartet?

**Comment by rockgobo** [comment]
select * from atlas.[Values]
where exists 
(
select * from atlas.Layers
where Parent_id = 'F709F252-230E-43D2-808E-606DC9C049E7'
AND Layer_id = atlas.[Values].Layer_id
AND Id not in ('F5F16D6F-F706-4690-BB3A-19CBE3476E66',
'E3AD3805-4224-454E-B194-1C30517A8D08',
'81008676-F409-4BFB-9A6E-44CDDAC2B4EC',
'25749D70-8F37-4539-A7B3-B8777052DA32',
'C6A289B2-185B-4A8E-88D7-BD7B2CDF785B',
'058E3FAC-A933-471F-8EFD-F8E5DBF0EED1')
)
AND Year = 2004
AND Region_id <> 24

**Comment by rockgobo** [comment]
Ich habe jetzt alle Kennzahlen die mit denen aus der Datei 
Daten-Sek_Onl_GS-Sek_weibl_+Absolv berichtigt_170201.xlsx im Datenblatt "berichtigte Kennzahlen Asolventen" übereinstimmen entfernt und die Daten aus diesem Excelblatt erneut geladen. 

Diese sollten jetzt nur noch zwischen 2005 und 2015 liegen und auch die Werte für die Regionen beinhalten.

**Comment by IngridStoehr** [comment]
Bei folgenden Kennzahlen stimmt es auf **Kreisebene** leider noch nicht, hier wird mit dem Jahr 2004 begonnen und mit 2014 geendet; die OFR-Ebene stimmt.

- SuS ohne Abschluss - Anteil 
- SuS mit Abschluss der Haupt-/Mittelschule - Anteil 
- SuS mit Abschluss der Haupt-/Mittelschule - Anteil ausländisch 
- SuS mit mittlerem Schulabschluss - Anteil 
- SuS mit mittlerem Schulabschluss - Anteil männlich 
- SuS mit mittlerem Schulabschluss - Anteil ausländisch 
- SuS mit allgemeiner Hochschulreife - Anteil 
- SuS mit allgemeiner Hochschulreife - Anteil männlich 
- SuS mit allgemeiner Hochschulreife - Anteil ausländisch
