### ISSUE TITLE
OFR-Werte fehlen - Schulbildung: Sekundarstufe

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#136]
Meines Wissens waren diese schon mal da und sind jetzt weg... es betrifft folgende Kennzahlen:

- SuS an Haupt-/Mittelschulen - Anteil männlich 
- SuS an Haupt-/Mittelschulen - Anteil ausländisch 
- Durchschnittliche Klassengröße an Haupt-/Mittelschulen 
- Lehrkräfte an Haupt-/Mittelschulen - Anzahl 
- Lehrkräfte an Haupt-/Mittelschulen - Anteil männlich 
- SuS an Realschulen - Anteil männlich 
- SuS an Realschulen - Anteil ausländisch 
- Durchschnittliche Klassengröße an Realschulen 
- Lehrkräfte an Realschulen - Anzahl 
- Lehrkräfte an Realschulen - Anteil männlich 
- SuS an Gymnasien - Anteil männlich 
- SuS an Gymnasien - Anteil ausländisch 
- Durchschnittliche Klassengröße an Gymnasien 
- Lehrkräfte an Gymnasien - Anzahl 
- Lehrkräfte an Gymnasien - Anteil männlich 
- SuS an Freien Waldorfschulen - Anteil männlich 
- SuS an Freien Waldorfschulen - Anteil ausländisch
- Durchschnittliche Klassengröße an Freien Waldorfschulen 
- Lehrkräfte an Freien Waldorfschulen - Anzahl 
- Lehrkräfte an Freien Waldorfschulen - Anteil männlich 

Also ziemlich viele... Hast Du die Werte noch "irgendwo"? Sie waren in der Ursprungstabelle von "ganz früher", d.h. diese waren noch nicht in der jetzigen Form aufbereitet. Vgl. Tabellenblatt "Schülerzahl" 
[OFR-Werte_KlassengrößeGS+ÜBQ_161208.xlsx](https://github.com/rockgobo/biloatlas/files/773382/OFR-Werte_KlassengrosseGS.UBQ_161208.xlsx)

Gib bitte Bescheid, wenn wir uns nochmals an die Aufbereitung setzen sollen!

**Comment by rockgobo** [comment]
Also gaaaanz früher habe ich noch keinen einzigen Oberfrankenwert eingelesen, ich habe daher keinerlei Artefakte aus denen sich diese herauslesen lassen :-)

Bin auch total durcheinander, da diese Zahlen in den alten Tabellen ganz anders heißen. Wenn ihr es schafft nach den Oberfrankendaten zu schürfen, würde ich das Gold dann einfach an mich nehmen und archivieren.

**Comment by IngridStoehr** [comment]
Dann lege ich meine Schürze an und schürfe ...

**Comment by IngridStoehr** [comment]
La voilà

[Daten-Sek_Onl_fehlende OFR-Werte_170215.xlsx](https://github.com/rockgobo/biloatlas/files/776296/Daten-Sek_Onl_fehlende.OFR-Werte_170215.xlsx)

**Comment by rockgobo** [comment]
Cool danke, hab sie gleich mit reingeladen
