### ISSUE TITLE
Legende: Leerzeichen zu Prozentzeichen - bei Tabelle, Angabe OFR-Durchschnitt nicht --> bitte vereinheitlichen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#137]

**Comment by rockgobo** [comment]
Ich nehme jetzt mal an, dass bei Prozentzeichen kein Leerzeichen erscheinen soll.

**Comment by IngridStoehr** [comment]
Ja, einheitlich kein Leerzeichen

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 14. Februar 2017 08:48
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Legende: Leerzeichen zu Prozentzeichen - bei Tabelle, Angabe OFR-Durchschnitt nicht --> bitte vereinheitlichen (#137)


Ich nehme jetzt mal an, dass bei Prozentzeichen kein Leerzeichen erscheinen soll.

**Comment by rockgobo** [comment]
Was ist mit DIN 5008?

**Comment by IngridStoehr** [comment]
Das ist eine never ending story! Ich habe jetzt nochmals geklärt, wir folgen der DIN und setzen eines. Danke der Nachfrage.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 14. Februar 2017 12:26
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Legende: Leerzeichen zu Prozentzeichen - bei Tabelle, Angabe OFR-Durchschnitt nicht --> bitte vereinheitlichen (#137)


Was ist mit DIN 5008?

**Comment by rockgobo** [comment]
http://www.annika-lamer.de/beliebte-rechtschreibfehler-das-leerzeichen/

**Comment by rockgobo** [comment]
Da wir alle Excel benutzen und Excel aber wohl Amerikaner gebaut haben, sind wir wohl alle ein wenig amerikanisiert :-) Im Deutschen ersetzen Abkürzungen wie "%" wohl die gesprochenen Einheiten "Prozent". Gilt diese neue Ansage auch für die Berichte von den Teilnehmerrückmeldungen?

**Comment by IngridStoehr** [comment]
Danke, das leite ich weiter… ;)

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 14. Februar 2017 14:23
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Legende: Leerzeichen zu Prozentzeichen - bei Tabelle, Angabe OFR-Durchschnitt nicht --> bitte vereinheitlichen (#137)


http://www.annika-lamer.de/beliebte-rechtschreibfehler-das-leerzeichen/

**Comment by IngridStoehr** [comment]
Nein, da mische ich mich jetzt nicht ein. Hier haben wir die restlichen Teilnehmerrückmeldungen ja ohne (wie im print Atlas) gemacht, das denke ich , wird so bleiben…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 14. Februar 2017 14:25
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Legende: Leerzeichen zu Prozentzeichen - bei Tabelle, Angabe OFR-Durchschnitt nicht --> bitte vereinheitlichen (#137)


Da wir alle Excel benutzen und Excel aber wohl Amerikaner gebaut haben, sind wir wohl alle ein wenig amerikanisiert :-) Im Deutschen ersetzen Abkürzungen wie "%" wohl die gesprochenen Einheiten "Prozent". Gilt diese neue Ansage auch für die Berichte von den Teilnehmerrückmeldungen?
