### ISSUE TITLE
Studium: OFR-Werte fehlen - werden noch geliefert (Montag, 20.2.)

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#139]

**Comment by IngridStoehr** [comment]
Hier sind die Werte, sie liegen auch im Austauschordner unter Studium.
[WebAtlas_Studium_OFR_170220.xlsx](https://github.com/rockgobo/biloatlas/files/789234/WebAtlas_Studium_OFR_170220.xlsx)

**Comment by IngridStoehr** [comment]
Bitte die Daten im Austauschordner nutzen.

**Comment by rockgobo** [comment]
DUPLIKATE!!!! ACHTUNG ACHTUNG, 
Folgende Layer sind doppelt in der Tabelle (alle Werte von 2004 - 1014), welche Daten soll ich denn laden? :-)
- Studierende - Anteil männlich: Ingenieurwesen
- Studierende - Anteil männlich: Kunst
- Studierende - Anteil männlich: Mathematik, Natur
- Studierende - Anteil männlich: Medizin, Gesundheit
- Studierende - Anteil männlich: Recht, Wirtschaft, Soziales
- Studierende - Anteil männlich: Sport
- Studierende - Anteil männlich: Sprache, Kultur

**Comment by IngridStoehr** [comment]
Sorry, die Männer waren doppelt und die Frauen haben gefehlt. Ich habe das nun berichtigt, die eine Hälfte heißt nun:
    Studierende - Anteil weiblich: Ingenieurwesen
    Studierende - Anteil weiblich: Kunst
    Studierende - Anteil weiblich: Mathematik, Natur
    Studierende - Anteil weiblich: Medizin, Gesundheit
    Studierende - Anteil weiblich: Recht, Wirtschaft, Soziales
    Studierende - Anteil weiblich: Sport
    Studierende - Anteil weiblich: Sprache, Kultur
