### ISSUE TITLE
Regionenansicht: maximale Länge der Balken bei zwei Jahren

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#140]
Folgendes, was ich bei der geschlossenen #129 geantwortet hatte
 _"Bei der Übertrittsquote an die Realschule wird in der Regionenansicht der Balken für BA Stadt 2005 als „Maximum“ genutzt (ist eigentlich der niedrigste Wert), sodass alle Balken im Liniendiagramm gleich groß sind…_ 
trifft auch auf einige (nicht alle!) Kennzahlen der Erwachsenenbildung: VHS in der Regionenansicht zu.

**Comment by rockgobo** [comment]
Ich scheine die Oberfrankenwerte für die Berechnung des Maximums nicht zu beachten.
