### ISSUE TITLE
Diagrammansicht: Einwohnerin und Einwohner pro km

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#143]
Hier ist die Überschneidung der Kreisnahmen noch etwas massiv... lässt sich das ändern? Falls nicht, bleibt immer noch die Möglichkeit "Ansicht nicht möglich, bitte andere Option wählen"...

**Comment by rockgobo** [comment]
Also ich werde für die Labels eine Ellipse anstelle der Kreisgleichung einbauen.

**Comment by IngridStoehr** [comment]
Das hört sich doch nach viel Aufwand an…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 21. Februar 2017 12:32
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Diagrammansicht: Einwohnerin und Einwohner pro km (#143)


Also ich werde für die Labels eine Ellipse anstelle der Kreisgleichung einbauen.

**Comment by rockgobo** [comment]
Das Problem die Elipsoide zu verwenden, war nur die Mathematik aus der Schule [radius1 * sin(r), radius2 * cos(r)] an der richtigen Stelle einzubauen. Allerdings löst es das Problem mit den Einwohnern nicht so wirklich, da das Getränge um die kleinen Bogenmasse (Also oben) einfach zu groß sind. Soweit kann man die Ellipse leider nicht strecken, dass das funktionieren würde. Momentan ist der Labeling-Algorithmus "einfach" umzusetzen, da die Positionen unabhängig von den anderen Werten berechnet werden kann. Um eine Verdeckung komplett auszuschließen müsste man einen Labeling-Algorithmus verwenden der global alle Werte mit in Betracht zieht. Das kostet richtig viel Zeit. Schau mal ob das so erträglich ist. Sieht jetzt schon ein wenig eierförmig aus. :-)

**Comment by IngridStoehr** [comment]
Ja, für mich ist das erträglich, wenn andere das nicht so sehen, dann steht diese Ansicht einfach nicht zur Verfügung.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 23. Februar 2017 12:42
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Diagrammansicht: Einwohnerin und Einwohner pro km (#143)


Das Problem die Elipsoide zu verwenden, war nur die Mathematik aus der Schule [radius1 * sin(r), radius2 * cos(r)] an der richtigen Stelle einzubauen. Allerdings löst es das Problem mit den Einwohnern nicht so wirklich, da das Getränge um die kleinen Bogenmasse (Also oben) einfach zu groß sind. Soweit kann man die Ellipse leider nicht strecken, dass das funktionieren würde. Momentan ist der Labeling-Algorithmus "einfach" umzusetzen, da die Positionen unabhängig von den anderen Werten berechnet werden kann. Um eine Verdeckung komplett auszuschließen müsste man einen Labeling-Algorithmus verwenden der global alle Werte mit in Betracht zieht. Das kostet richtig viel Zeit. Schau mal ob das so erträglich ist. Sieht jetzt schon ein wenig eierförmig aus. :-)
