### ISSUE TITLE
Startseite: Themenbereiche - Linkfunktion verdeutlichen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#147]
Lässt sich auf der Startseite außer durch die Unterstreichung beim Mouseover noch deutlicher kennzeichnen, dass es sich hierbei um Links handelt? Ggf. wie bei der Regionenansicht die Pfeile am Anfang? (oder stehen diese explizit für Ausklappen?)

**Comment by rockgobo** [comment]
Die Pfeile sind nur Dekoration, die kann ich überall hinhängen.
