### ISSUE TITLE
Regionenansicht: Anordnung der Karten und des Textes

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#148]
Bitte die Reihenfolge der Karten austauschen, erst die Karte mit den Einrichtungen (links) und dann die OFR-Karte.
Bitte den Text im blauen Kästchen über die Karten (oben) und die gesamte Seitenbreite nutzen.

Ziel ist u.a., dass die Themenbereiche bei einer "normalen" Bildschirmansicht ohne Scrollen sichtbar sind. Ggf. müssten dafür die Karten verkleinert werden? Eine Überlegung wäre noch, die OFR-Karte (rechts) zu "halbieren" und dann den blauen Kasten in die gewonnene Hälfte zu packen?
Hier sollten wir erst drüber reden...

**Comment by IngridStoehr** [comment]
Aktualisiert:
Reihenfolge der Karte austauschen
Text über Karten
Buttons unter Kreisgebietskarte

**Comment by IngridStoehr** [comment]
neuer Textvorschlag:

In der **Regionenansicht** können Sie sich für das ausgewählte Kreisgebiet aller im webAtlas BildungsLandschaft Oberfranken verfügbaren Kennzahlen im Zeitverlauf im Vergleich zu Oberfranken anzeigen lassen. Wählen Sie dazu einen **Themenbereich** aus. _[Könnte oberhalb der Auflistung der Themenbereiche unter der Karte eine "Überschrift" "Themenbereiche" ergänzt werden?]_
Zudem können Sie unter **Detailansicht** einen differenzierten Blick auf die räumliche Verteilung der verschiedenen Bildungseinrichtungen vor Ort gewinnen. Ergänzend finden Sie die entsprechenden Adressinformationen zu den Einrichtungen.
Das zur Verfügung gestellte **Kreisprofil** stammt aus dem Atlas BildungsLandschaft Oberfranken (PDF-Version) und beinhaltet einzelne aufbereitete Kennzahlen je Themenbereich für das gewählte Kreisgebiet.

Der Text ist nun etwas länger, aber wenn er über die gesamte Seitenbreite geht, passt es vielleicht doch?
Vielleicht könnte man die wichtigen Begriffe noch fett schreiben?

**Comment by rockgobo** [comment]
Ich habe die letzten beiden highlights (Detailansicht und Kreisprofil) dadurch hervorgehoben, indem ich die beiden als Link zu den jeweiligen Features gesetzt habe.

**Comment by IngridStoehr** [comment]
Gefällt mir!
Ein kleiner Fehler war wohl in der Vorlage, das „r“ bei „aller“ müsste weg…

In der Regionenansicht können Sie sich für das ausgewählte Kreisgebiet aller im webAtlas BildungsLandschaft Oberfranken

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Montag, 6. März 2017 11:56
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Regionenansicht: Anordnung der Karten und des Textes (#148)


Ich habe die letzten beiden highlights (Detailansicht und Kreisprofil) dadurch hervorgehoben, indem ich die beiden als Link zu den jeweiligen Features gesetzt habe.

**Comment by rockgobo** [comment]
Hab den Schreibfehler noch entfernt.
