### ISSUE TITLE
Festlegung Kategorienanzahl: Standardeinstellung bei 3 Kategorien und Textergänzung

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#150]
Bitte die STandardeinstellung von 9 Kategorien auf 3 Kategorien ändern.
Bitte folgenden Text beim Symbol ergänzen:
Auswahl der Kategorienanzahl

**Comment by rockgobo** [comment]
Ähmmm das ist kein Startwert... das ist die Anzahl von Kategorien, die momentan gewählt wurden. Aber ich kann da auch immer 3 reinschreiben.

**Comment by IngridStoehr** [comment]
Könntest Du noch den Text ergänzen? Danke!

**Comment by rockgobo** [comment]
Ähhh wo kommt der Text hin? Auswahl der Kategorienanzahl steht doch da?

**Comment by IngridStoehr** [comment]
Gewünscht war noch eine Kennzeichnung auf der ersten Ebene, damit man weiß, dass man über das Rädchen die Anzahl der Kategorien ändern kann. Vielleicht über die Mouse over Funktion einblenden?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. März 2017 14:58
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; State change <state_change@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Festlegung Kategorienanzahl: Standardeinstellung bei 3 Kategorien und Textergänzung (#150)


Ähhh wo kommt der Text hin? Auswahl der Kategorienanzahl steht doch da?

**Comment by rockgobo** [comment]
Achso, dann kann ich den langen Text bei der Anzeige wieder rausmachen und dort einfach "Kategorienanzahl" schreiben?

**Comment by IngridStoehr** [comment]
Ja, sorry für das Misverständnis.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Montag, 6. März 2017 08:12
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; State change <state_change@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Festlegung Kategorienanzahl: Standardeinstellung bei 3 Kategorien und Textergänzung (#150)


Achso, dann kann ich den langen Text bei der Anzeige wieder rausmachen und dort einfach "Kategorienanzahl" schreiben?

**Comment by rockgobo** [comment]
Das Icon hat nun ein ganz einfachen Tooltip. Das Label für die Kategorienanzahl habe ich wieder gekürzt.

**Comment by IngridStoehr** [comment]
Jetzt steht in der Auswahl der Kategorienanzahl zwar 3, angezeigt werden aber weiterhin 9 Kategorien als Standardeinstellung.
Der Tooltip ist leider doch nicht ausreichend. Gewünscht ist, dass das Symbol für die Kategorienauswahl neben "Keine Angabe" kommt und mit einem sichtbaren Text ergänzt wird (Auswahl Kategorienanzahl).

**Comment by IngridStoehr** [comment]
Dieses issue ist uns durchgerutscht - wie oben geschrieben ist gewünscht, dass das Symbol für die Kategorienauswahl neben "Keine Angabe" kommt und mit dem (ohne Tooltip) sichtbaren Text "Auswahl Kategorienanzahl" ergänzt wird. Danke.
