### ISSUE TITLE
Ringdiagramm: Abschneiden der Zahlenwerte bei zwei Kennzahlen und "langen" Werten

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#153]
Aufgefallen ist dies z.B. bei Erwachsenenbildung: VHS - Gesamteinnahmen und Anteil Teilnahmegebühren, die erste Zahl wird nicht ganz angezeigt. Geht zweizeilig oder einfach ausblenden?

**Comment by IngridStoehr** [comment]
Wir beschließen: Auf die Zahlenwerte wird in der Anzeige verzichtet, sie sind über Mouseover erkennbar oder in der Tabelle.
Ellipse kommt raus, wenn der Osterhase verzichten kann.

**Comment by rockgobo** [comment]
Der Osterhase muss jetzt wo anders nach Eiern suchen :-) Die Labels werden nun nur beim Mouseover angezeigt.
