### ISSUE TITLE
Regionenansicht: Wanderungssaldo ausländische Bevölkerung

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#156]
Bitte y-Achse in Negativbereich erweitern, da negative Werte vorkommen.

**Comment by rockgobo** [comment]
Das Minimum wird anhand der Daten berechnet und es wird auch nichts abgeschnitten, was genau ist denn die Erwartunghaltung? Warum stört ihr euch an der momentanen Ansicht?

**Comment by IngridStoehr** [comment]
Das war vorbeugend gedacht....
Störend könnte empfunden werden, dass die angezeigten Werte kleiner 0 sind (z.B. -286 für OFR), der kleinste auf der y-Achse dargestellte Wert aber 0 ist. Wir können auch warten, ob sich tatsächlich jemand daran stört... ich schließe das issue vorerst.
