### ISSUE TITLE
Kennzahl: Durchschnittliche Klassengröße an Haupt-/Mittelschulen - Keine Angabe anzeigen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#157]
Für 2010-2013 und 2015 liegen keine Werte vor, in der Regionenansicht wird hier eine 0 angezeigt. Bitte hier - wie zwischen 2005 und 2010 gar nichts anzeigen.

**Comment by rockgobo** [comment]
Ich habe die Werte aus dem Jahr 2015 und 2010-2013 mit dem Wert 0 entfernt.
