### ISSUE TITLE
Studium: folgende Kennzahlen werden fälschlicherweise ab 2004 angezeigt

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#158]
...und alle habe hier den Wert 0, daher bitte erst ab 2005 anzeigen, wie die OFR-Werte

##Studium
Studierende - Anteil aus dem Kreisgebiet 
Studierende - Anteil aus Bayern 
Studierende - Anteil aus anderen Bundesländern 
Studierende - Anteil aus dem Ausland

**Comment by IngridStoehr** [comment]
Gleiches gilt für die Kreisebene folgender Kennzahlen:
##Studium
Personen mit Hochschulabschluss - Anzahl 
Personen mit Hochschulabschluss - Anteil: Sprache, Kultur 
Personen mit Hochschulabschluss - Anteil: Recht, Wirtschaft, Soziales 
Personen mit Hochschulabschluss - Anteil: Mathematik, Natur 
Personen mit Hochschulabschluss - Anteil: Medizin, Gesundheit 
Personen mit Hochschulabschluss - Anteil: Ingenieurwesen 
Personen mit Hochschulabschluss - Anteil: Kunst 
Personen mit Hochschulabschluss - Anteil: Sport 

Erstsemester - Anzahl mit HZB aus Kreisgebiet 
Erstsemester - Anteil Hochschule in Bayern 
Erstsemester - Anteil Hochschule in Deutschland

**Comment by rockgobo** [comment]
Kontrollieren ob die 0 auch in den Daten liegen. Wenn ja entfernen.
