### ISSUE TITLE
Daten aktualisieren wegen Nachkommastellen für folgende Kennzahlen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#159]
## Strukturelle Rahmendaten
Jugendquotient
Altenquotient
Durchschnittsalter
Prognose Jugendquotient
Prognose Altenquotient

## Frühkindliche Bildung
Personal mit Qualifizierungskurs Kindertagespflege - Anteil 

## Schulbildung Primarstufe
SuS an Grundschulen - Anteil männlich 
SuS an Grundschulen - Anteil ausländisch
Durchschnittliche Klassengröße an Grundschulen 
Lehrkräfte an Grundschulen - Anteil männlich 

## Schulbildung Sekundarstufe
SuS an Haupt-/Mittelschulen - Anteil ausländisch 
Durchschnittliche Klassengröße an Haupt-/Mittelschulen 
Lehrkräfte an Haupt-/Mittelschulen - Anteil männlich (bei Anteil weiblich ist die Kommastelle da???)
SuS an Realschulen - Anteil männlich 
SuS an Realschulen - Anteil ausländisch 
Durchschnittliche Klassengröße an Realschulen 
Lehrkräfte an Realschulen - Anteil männlich 
SuS an Gymnasien - Anteil männlich 
SuS an Gymnasien - Anteil ausländisch 
Durchschnittliche Klassengröße an Gymnasien 
Lehrkräfte an Gymnasien - Anteil männlich 
SuS ohne Abschluss - Anteil 
SuS mit Abschluss der Haupt-/Mittelschule - Anteil 
SuS mit Abschluss der Haupt-/Mittelschule - Anteil ausländisch 
SuS mit mittlerem Schulabschluss - Anteil 
SuS mit mittlerem Schulabschluss - Anteil männlich 
SuS mit mittlerem Schulabschluss - Anteil ausländisch 
SuS mit allgemeiner Hochschulreife - Anteil 
SuS mit allgemeiner Hochschulreife - Anteil männlich 
SuS mit allgemeiner Hochschulreife - Anteil ausländisch 

und wie besprochen für die Kennzahlen zu Anteilen der

**Comment by rockgobo** [comment]
Die Daten der Erwachsenenbildung liegt in der Datei: Values_Anteile.xlsx

**Comment by rockgobo** [comment]
Manche Nachkommastellen muss man sich sehr schwer erkaufen

**Comment by IngridStoehr** [comment]
Oh ja, da hast Du vollkommen Recht, da hätte ich auch gerne drauf verzichtet. Lädst Du diese values auch noch herunter und gibst mir Bescheid, wo sie liegen?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. März 2017 14:48
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Daten aktualisieren wegen Nachkommastellen für folgende Kennzahlen (#159)


Manche Nachkommastellen muss man sich sehr schwer erkaufen

**Comment by IngridStoehr** [comment]
Die Werte sind mit Kommastelle in der Spale Value new eingefügt.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. März 2017 14:47
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Daten aktualisieren wegen Nachkommastellen für folgende Kennzahlen (#159)


Die Daten der Erwachsenenbildung liegt in der Datei: Values_Anteile.xlsx

**Comment by rockgobo** [comment]
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT
	l.Name 
	,[Region_id]
	,r.Name
      ,[Layer_id]
      ,[Value]
      ,[Year]
  FROM [Bilo].[atlas].[Values] val
  join atlas.Layers l on val.Layer_id = l.id
  join Regions r on r.Id = val.Region_id
  WHERE l.Name in (
  'Jugendquotient',
'Altenquotient',
'Durchschnittsalter',
'Prognose Jugendquotient',
'Prognose Altenquotient',
'Personal mit Qualifizierungskurs Kindertagespflege - Anteil',
'SuS an Grundschulen - Anteil männlich',
'SuS an Grundschulen - Anteil ausländisch',
'Durchschnittliche Klassengröße an Grundschulen',
'Lehrkräfte an Grundschulen - Anteil männlich',
'SuS an Haupt-/Mittelschulen - Anteil ausländisch',
'Durchschnittliche Klassengröße an Haupt-/Mittelschulen',
'Lehrkräfte an Haupt-/Mittelschulen - Anteil männlich',
'SuS an Realschulen - Anteil männlich',
'SuS an Realschulen - Anteil ausländisch',
'Durchschnittliche Klassengröße an Realschulen',
'Lehrkräfte an Realschulen - Anteil männlich',
'SuS an Gymnasien - Anteil männlich',
'SuS an Gymnasien - Anteil ausländisch',
'Durchschnittliche Klassengröße an Gymnasien',
'Lehrkräfte an Gymnasien - Anteil männlich',
'SuS ohne Abschluss - Anteil',
'SuS mit Abschluss der Haupt-/Mittelschule - Anteil',
'SuS mit Abschluss der Haupt-/Mittelschule - Anteil ausländisch',
'SuS mit mittlerem Schulabschluss - Anteil',
'SuS mit mittlerem Schulabschluss - Anteil männlich',
'SuS mit mittlerem Schulabschluss - Anteil ausländisch',
'SuS mit allgemeiner Hochschulreife - Anteil',
'SuS mit allgemeiner Hochschulreife - Anteil männlich',
'SuS mit allgemeiner Hochschulreife - Anteil ausländisch') 
ORDER BY l.NAME, Year

**Comment by rockgobo** [comment]
Ich habe die Daten in das Verzeichnis "00_Austausch/Bilo/Bilo-atlas/Kommastellen"

**Comment by IngridStoehr** [comment]
Ich habe die Werte jetzt in dem Dokument 
[#159Nachkommastellen_170308.xlsx](https://github.com/rockgobo/biloatlas/files/827154/159Nachkommastellen_170308.xlsx) ergänzt, alle mit einer sichtbaren Kommastelle; 
Zusätzlich zu den von Dir reinkopierten habe ich noch einzelne weitere ergänzt, wo mir aufgefallen ist, dass sie aktuell im webAtlas nicht stimmen, hier fehlt der Layer aber:
Lehrkräfte an Grundschulen - Anzahl --> nur für Oberfranken (ist auch als ganze Zahl ohne Kommastelle eingetragen)
SuS an Haupt-/Mittelschulen - Anteil männlich --> für Kreisgebiete

Soll ich wegen der Tabelle vorbeikommen?

**Comment by IngridStoehr** [comment]
Es fehlen noch die Werte inkl. Nachkommastelle zu diesen beiden Kennzahlen:
IHK-Auszubildende - Anteil mit Wohnsitz im Kreisgebiet des Arbeitsortes 
HWK-Auszubildende - Anteil mit Wohnsitz im Kreisgebiet des Arbeitsortes

**Comment by IngridStoehr** [comment]
Daten sind im Dokument #159Nachkommastellen_170308.xlsx ergänzt.

**Comment by IngridStoehr** [comment]
es fehlt noch:
Lehrkräfte an Grundschulen - Anzahl - für Oberfranken--> Fehlermeldung

**Comment by rockgobo** [comment]
> es fehlt noch:
Lehrkräfte an Grundschulen - Anzahl - für Oberfranken--> Fehlermeldung

Was meinst du mit Fehlermeldung? Ist das eine Notiz für dich oder wirft die Software einen Fehler?

**Comment by IngridStoehr** [comment]
Ich habe die Daten in meiner csv - in diesem Fall fehlen nur die OFR-Werte, d.h. ich entferne die anderen nicht und will jene in der csv ergänzen, er lädt aber 0 datensätze hoch...

**Comment by rockgobo** [comment]
Wo liegt denn die Datei, dann schau ich mir den Fall mal an.

**Comment by IngridStoehr** [comment]
Z:\00_Austausch\BiLO\BiLO-Atlas\Kommastellen\#159Nachkommastellen_170403.csv

**Comment by rockgobo** [comment]
Ich weiß nicht wo du die ID der Kennzahl her hast, aber die ist falsch, daher lädt er auch nichts :-)

12FF87C4-15AF-49AB-B2B5-4AD533F90F11

**Comment by IngridStoehr** [comment]
o.k. danke!

**Comment by IngridStoehr** [comment]
Könntest Du kurzfristig folgende Frage antworten: Geht es, dass ich nur Kreisdaten hochlade und die OFR-Werte drinlasse? Ich kann dann ja nicht auf Alle Werte entfernen gehen...?
