### ISSUE TITLE
Regionenansicht: Name Kreisgebiet in Balken bitte ohne Abkürzung 

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#162]
Bitte folgende Schreibweisen nutzen:
Stadt Bamberg
Stadt Bayreuth
Stadt Coburg
Stadt Hof
Landkreis Bamberg
Landkreis Bayreuth
Landkreis Coburg
Landkreis Forchheim
Landkreis Hof
Landkreis Kronach
Landkreis Kulmbach
Landkreis Lichtenfels
Landkreis Wunsiedel i. Fichtelgebirge

**Comment by rockgobo** [comment]
Überschrift im Badge

**Comment by rockgobo** [comment]
Neuen Filter erzeugt, der Lkr. in Landkreis ersetzt.
