### ISSUE TITLE
Regionenansicht: Achsenbeschriftung y-Achse - Bsp. Bevölkerungszahl zu eng

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#170]
Optionen
a) Abstand vergrößern (sieht dann bei anderen Kennzahlen komisch aus)
b) könnten diese Zahlen in 1000 angegeben werden, ist dafür die Aufbereitung der Tabellen notwendig? (lass uns drüber reden...)

**Comment by rockgobo** [comment]
Abstand vergrößern.

**Comment by rockgobo** [comment]
Abstand wurde erhöht
