### ISSUE TITLE
Regionenansicht x-Achse: Neben 0 und Maximalwert z.T. weitere einzelne Werte angezeigt, bitte entfernen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#172]
Bsp. Übertrittsquote an Realschule, hier taucht 20% auf... (unabhängig vom Kreis)

**Comment by IngridStoehr** [comment]
Gleiches gilt für die Durchschnittliche Klassengröße an Haupt-/Mittelschulen

**Comment by rockgobo** [comment]
Man nennt so etwas eine Hilfslinie, nicht ganz unüblich diese in Diagrammen zu verwenden um dem Nutzer eine gewisse Hilfestellung bei der Interpretation der Daten zu geben. Aber ich mache sie gerne raus.
