### ISSUE TITLE
Regionenansicht: y-Achse bei der Kennzahl "Freie Waldorfschulen - Anzahl" geht ins Negative, ...

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#173]
... hier bitte nur bis 0 und lediglich die Hilfslinien ein bisschen verlängern wie etwa bei "SuS an Freien Waldorfschulen - Anteil ausländisch"

**Comment by rockgobo** [comment]
ich habe seither vom Minimum 5 abgezogen. Jetzt ziehe ich 10% vom Minimalwert ab und ziehe nochmal zusätzlich 0.5 ab. Die Nulllinie wird jetzt auch ein wenig deutlicher dargestellt, damit man besser sieht, wenn die Werte Null sind.
