### ISSUE TITLE
Detailansicht: Adressen Erwachsenenbildung

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#176]
... hier sollte bei den Nebenstellen der Volkshochschulen ein vhs ergänzt werden, da die Ortsnamen allein wenig aussagen. Dies ist in der Adressdatei erfolgt. Bitte neu hochladen. Liegt auch im Austauschordner
[Adressen_Masterliste_Stand Befragung170125_170316.xlsx](https://github.com/rockgobo/biloatlas/files/847046/Adressen_Masterliste_Stand.Befragung170125_170316.xlsx)

**Comment by IngridStoehr** [comment]
wie gestern besprochen, hat sich die Anzahl der vhs-Nebenstellen von 2013 (aktuell hochgeladen) auf 2014 (das wollen wir) geändert. Die Adressdatei enthält nun eine neue Spalte --> Spalte AO, VHS: Adressdatenzeitpunkt, hier ist das Jahr 2014 eingetragen. Bitte nur die Volkshochschuladressen hochladen, die hier ein 2014 stehen haben. Danke.

**Comment by rockgobo** [comment]
USE [Bilo]
GO

UPDATE a
   SET [Location] = geography::Point(cast(b.y as float), cast(b.x as float), 4326).ToString() 
FROM [dbo].[Locations] a 
INNER JOIN [dbo].[Locations] b
on a.Id = b.Id
