### ISSUE TITLE
Regionenansicht: Studium - Punkte statt Linien für folgende Kennzahlen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#177]
Für diese Kennzahlen
- Erstsemester - Anzahl mit HZB aus Kreisgebiet
- Erstsemester - Anteil Hochschule in Oberfranken
- Erstsemester - Anteil Hochschule in Bayern
- Erstsemester - Anteil Hochschule in Deutschland
liegen nur drei Jahre vor: 2005, 2010, 2014, allerdings für alle Kreisgebiete in OFR, da es sich um die Studierenden in den Kreisen (nicht an den Unis) handelt. 
Bitte in der Regionenansicht im Diagramm Punkte und keine Linien angeben (bisher unterschiedlich gehandhabt, bei Kreisen mit Unis (Bsp. Bamberg) sind Liniendiagramme, bei Kreisen ohne Unis sind schon Punkte (Bsp. Kulmbach)

**Comment by rockgobo** [comment]
Daten der Jahre mit den Nullen löschen.
