### ISSUE TITLE
Themenansicht: Kartendarstellung - Bevölkerungsprognose prozentual

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#182]
Der Landkreis Forchheim wird in der Karte weiß (z.B. 2024), da 0,0%, allerdings gibt es weiß dann nicht in der Legende. Bitte Farbe weiß in den angezeigten Fällen ergänzen.

**Comment by rockgobo** [comment]
Diese Skala ist ein wenig kniffliger. Da die Skala von -3.0 bis 0.9 geht ist weiß an der Stelle irreführend, da sie einen einzelnen Wert representiert und man sie mitten in die Skala einbauen müsste. Ich habe die Logik für die Anzeige einer weißen Fläche in so fern geändert, dass man vorne nur einen Weißton in der Skala hat, wenn die kleinste Zahl in den Daten eine 0 ist. 
Bei Bevölkerungsprognose wird daher jetzt richtigerweise kein weiß angezeigt, weder in der Karte noch der Skala.
