### ISSUE TITLE
Themenansicht: Breite graues Kästchen (Jahreszahl) im Jahr 2011 etwas kleiner

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#183]

**Comment by rockgobo** [comment]
Versteh ich nicht...

**Comment by IngridStoehr** [comment]
Klick mal die Jahre von 2015 nach unten in der Kartenansicht durch und achte auf das graue Kästchen, in 2011 verkleinert es sich...

**Comment by rockgobo** [comment]
Nicht euer Ernst?

**Comment by IngridStoehr** [comment]
... kommt nicht von mir.

**Comment by rockgobo** [comment]
Da muss ich sogar mein Hirn anstrengen, da ich glaube, das eine feste Breite nicht ganz so gut ist (responsives design und so)
