### ISSUE TITLE
Alle Kennzahlen zu Freien Waldorfschulen --> bei der Stadt Bayreuth wird fälschlicherweise 0 angezeigt, müsste "Keine Angabe" sein - Ausnahme...

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#185]
...ist das Jahr 2005, hier gab es noch eine Freie Waldorfschule, die dann bis 2010 geschlossen wurde.
Das sind die Kennzahlen:
- [x] Freie Waldorfschulen - Anzahl
- [x] Gesamtzahl SuS an Freien Waldorfschulen
- [x] SuS an Freien Waldorfschulen - Anteil männlich
- [x] SuS an Freien Waldorfschulen - Anteil weiblich
- [x] SuS an Freien Waldorfschulen - Anteil ausländisch
- [x] Durchschnittliche Klassengröße an Freien Waldorfschulen
- [x] Lehrkräfte an Freien Waldorfschulen - Anzahl
- [x] Lehrkräfte an Freien Waldorfschulen - Anteil männlich
- [x] Lehrkräfte an Freien Waldorfschulen - Anteil weiblich

**Comment by rockgobo** [comment]
Ich habe das zwar schon gelöscht, aber warum ist die Anzahl denn "keine Angabe" wenn es doch Fakt ist, dass es 0 gibt?

**Comment by IngridStoehr** [comment]
Richtig, Anzahl müsste nach 2005 "0" sein und die dann folgenden Kennzahlen "Keine Angabe", sorry.
