### ISSUE TITLE
Kommastelle hinterlegt, wird aber nicht angezeigt

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#188]
Jugendquotient
Altenquotient
Prognose Jugendquotient
Prognose Altenquotient

**Comment by IngridStoehr** [comment]
Durchschnittsalter

**Comment by rockgobo** [comment]
Sind das alle oder nur die mit ",0" am Ende?

IngridStoehr <notifications@github.com> schrieb am Do., 30. März 2017,
12:37:

**Comment by IngridStoehr** [comment]
hier wird in der neuen Adminansicht eine Kommastelle angezeigt, wenn die Zahl hinter dem Komma NICHT 0 ist. Die 0 müsste "produziert" werden.

**Comment by rockgobo** [comment]
Ok, hier die jetzige Implementierung der Nachkommastellen. Die Anzeige ist abhängig von der Einheit. Jede Zahl, die nicht die Einheit % hat wird auf eine Ganzzahl gerundet. %-Zahlen werden auf (ich glaube) 2 Stellen gerundet. 
Ich kann auch nicht einfach die Zahlen so übernehmen, da manche Daten von euch bis zu 5 Nachkommastellen haben. 
Falls außer den % Einheiten noch Zahlen mit Nachkommastellen angezeigt werden sollen müssen wir uns eine Lösung einfallen lassen.

**Comment by IngridStoehr** [comment]
Ja, leider gibt es diese Zahlen ohne Einheit Prozent, die eine Nachkommastelle haben sollten. (Wir hatten uns auf eine Stelle geeinigt). Die vier oben genannten:
Jugendquotient
Altenquotient
Prognose Jugendquotient
Prognose Altenquotient
sowie
Durchschnittsalter
sowie
Durchschnittliche Klassengröße [alle Schultypen, d.h. Grundschule, Mittelschule, Realschule, Gymnasium, Waldorfschule]

**Comment by rockgobo** [comment]
Die Anzahl der Nachkommastellen ist nun über das Backend einstellbar. Jetzt werde ich das Frontend so umbauen, dass diese Einstellungen übernommen werden. Damit lässt sich für jede einzelne Kennzahl beliebig und ganz flexibel einstellen wie viele Kommastellen man sieht.

**Comment by rockgobo** [comment]
http://localhost/biloAtlas/#/admin/layers/ 

In den Layers könnt ihr jetzt selbst die Nachkommastellen bestimmen. Viel Spaß beim konfigurieren :-)

**Comment by IngridStoehr** [comment]
Alle % Einheiten  bleiben aber mit einer Nachkommastelle, oder? Wir müssen sie nicht wieder alle anklicken...

Und bei den obengenannten Ausnahmen, wenn ich da eine 1 für eine Nachkommastelle reinschreibe, tut sich gar ncihts...

**Comment by rockgobo** [comment]
Oh ja, mein Fehler hab vergessen den Webservice hochzuladen. Muss das mal Automatisieren, wenn es ein wenig ruhiger geworden ist. Das ist immer ärgerlich, für alle beteiligten. Tut mir leid. Morgen funktioniert es.

**Comment by rockgobo** [comment]
Mit dem neuen Service geht es jetzt wie geschmiert. Ich habe die Kennzahlen oben kurz angepasst und falls noch was ist einfach über den Adminbereich ändern.

**Comment by rockgobo** [comment]
Den Mouseover auf der Karte und dem Kuchendiagram konnte ich in dem Zusammenhang auch so anpassen, dass er nun auch die Nachkommastellen aufgrund der Konfiguration anzeigt.

**Comment by IngridStoehr** [comment]
Du bist der Wahhsinn!

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 4. April 2017 08:30
An: rockgobo/biloatlas <biloatlas@noreply.github.com>
Cc: Stöhr, Ingrid <ingrid.stoehr@lifbi.de>; Author <author@noreply.github.com>
Betreff: Re: [rockgobo/biloatlas] Kommastelle hinterlegt, wird aber nicht angezeigt (#188)


Den Mouseover auf der Karte und dem Kuchendiagram konnte ich in dem Zusammenhang auch so anpassen, dass er nun auch die Nachkommastellen aufgrund der Konfiguration anzeigt.
