### ISSUE TITLE
Themenansicht & Regionenansicht: "Hinweis zum Wechseln"

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#191]
Bitte in der Themenansicht ein Infokästchen ergänzen mit folgendem Text:

Für den vertieften Blick in eine Region und die Darstellung im der Kennzahl im Zeitverlauf klicken Sie bitte auf Regionen. 
[Und bitte "Regionen" in diesem Text auch verlinken; Zur Platzierung: ggf. über "Weitere Kennzahl hinzufügen"?]

Bitte in der Regionenansicht bitte wie folgt:
Um die Kennzahl auf einen Blick in den verschiedenen Kreisgebieten Oberfrankens zu sehen, klicken Sie bitte auf Themen. 
[Hier bitte "Themen" in diesem Text auch verlinken; Zur Platzierung: ggf. unter den Link zum ausgewählten Themenbereich?]

**Comment by rockgobo** [comment]
"Regionen" kann man eigentlich nicht so schreiben, da es 16 verschiedene "Regionen" auf die man klicken kann. verlinken kann ich nur auf eine eindeutige Region. Mann sollte vielleicht in dem Text eher schreiben... klicken sie auf eine der Regionen in der Karte oder in der Regionennamen in der Tabellendarstellung.

Oder soll ich in beiden Fällen auf ... ähmm .. die "erste" Region und das "erste" Thema verlinken?

**Comment by rockgobo** [comment]
ahh ok auf der Startseite haben wir auch schon so einen link eingebaut, dann nehme ich einfach diesen.

**Comment by rockgobo** [comment]
....  und die Darstellung im der Kennzahl im Zeitverlauf klicken ...

ich habe das erste "im" weggelassen, da es nach meiner nach ein Schreibfehler war :-)

**Comment by IngridStoehr** [comment]
Bitte noch eine kleine Änderung im Text bei der Regionenansicht:

Um einzelne Kennzahlen auf einen Blick in den verschiedenen Kreisgebieten Oberfrankens zu sehen, klicken Sie bitte auf Themen.

Danke!

**Comment by rockgobo** [comment]
Sollte das nicht heißen:
Um einen Blick auf die einzelnen Kennzahlen in den verschiedenen
Kreisgebieten Oberfrankens zu sehen, klicken Sie bitte auf Themen?

IngridStoehr <notifications@github.com> schrieb am Di., 25. Apr. 2017,
09:20:

**Comment by IngridStoehr** [comment]
Ja, das hört sich besser an, danke!

**Comment by rockgobo** [comment]
Schöne Grüsse auf Dubrovnik 😊

IngridStoehr <notifications@github.com> schrieb am Di., 25. Apr. 2017,
09:33:

**Comment by IngridStoehr** [comment]
Danke. ???
