### ISSUE TITLE
Kommastellen vereinheitlichen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#21]
Bei der Anzeige des Durchschnitts und unten in der Legende bei Prozentzahlen bitte einheitlich eine Kommastelle, bei absoluten Zahlen keine Kommastellen.

**Comment by rockgobo** [comment]
Irgendwie war ich seither bei 2 kommastellen für die Prozentzahlen?

**Comment by IngridStoehr** [comment]
Gerade werden aber doch eine oder keine angezeigt, nur beim Durchschnitt sind zwei... Ich wäre für einheitlich eine.

**Comment by rockgobo** [comment]
Stimmt bei der Karte haben wir auch gesagt, eine Nachkommastelle. Ich ziehe es jetzt bei Prozenten überall auf eine Nachkommastelle.

**Comment by IngridStoehr** [comment]
Durchschnittliche Klassengröße bitte mit einer Kommastelle.

**Comment by IngridStoehr** [comment]
Bitte bei ursprünglich ganzen Zahlen keine künstliche Kommastelle generieren.

**Comment by rockgobo** [comment]
Neuer Filter eingebaut.
