### ISSUE TITLE
Bitte Grün wieder zurückändern!!

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#23]

**Comment by rockgobo** [comment]
Das musst du mir morgen mal genauer erklären...

**Comment by IngridStoehr** [comment]
Das hat sich erledigt, ich habe (erstmals) meinen Laptop als Zweitbildschirm genutzt und dort den Atlas geöffnet und da sahen die Farben ganz anders aus, Johannes hat mir erklärt, dass dies daran liege, dass sie nicht "Farbecht" seien... Auf dem großen Bildschirm ist alles gut :)
