### ISSUE TITLE
Detailansicht der Einrichtungen: Rückkehrmöglichkeit zu Gesamtansicht wäre schön

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#25]
Bisher ist es nicht möglich, dass ich von einer ausgewählten Ansicht (z.B. nur Berufsschulen) wieder zur Ansicht aller Einrichtungen wechsle.

**Comment by rockgobo** [comment]
Man kann noch einmal auf denselben Filter drücken, damit man wieder alles sieht, aber ich baue noch eine Möglichkeit ein, alle wieder anzuzeigen.
