### ISSUE TITLE
Machen die Nachkommastellen bei einem Durchschnitt über Ganzzahlen Sinn?

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#3]
Durchschnitt über zugezogenene Personen ist ein Beispiel wo die Anzeige 2642.17 vielleicht nicht so sinnvoll ist. Denkbar wäre Median oder Runden.

**Comment by IngridStoehr** [comment]
Bitte bei absoluten, ganzen Zahl die Kommastellen weglassen.

**Comment by IngridStoehr** [comment]
Jetzt erst sehe ich Deinen Kommentar oben, ja bitte runden. Danke.
