### ISSUE TITLE
Seitenansicht: Lifbi Logo

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#30]
![lifbi_logo](https://cloud.githubusercontent.com/assets/20164709/19468883/22138dce-9519-11e6-90ae-ca002fdf1989.jpg)
![lifbi](https://cloud.githubusercontent.com/assets/20164709/19468902/368f3190-9519-11e6-96b4-5e5783b02218.png)

**Comment by rockgobo** [comment]
Dann soll ich das Logo unten durch dieses ersetzen? Dort steht ja ein Logo mit dem Titel "Eine Studie am"

**Comment by IngridStoehr** [comment]
Ja, bitte ersetzen. Danke!

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Montag, 14. November 2016 15:07
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Seitenansicht: Lifbi Logo (#30)

Dann soll ich das Logo unten durch dieses ersetzen? Dort steht ja ein Logo mit dem Titel "Eine Studie am"

**Comment by rockgobo** [comment]
Neues Logo hinzugefügt
