### ISSUE TITLE
Link zu pdf Print-Kreisprofilen in Regionenansicht

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#32]

**Comment by rockgobo** [comment]
Noch nicht ganz hübsch aber funktioniert. ACHTUNG: Ist erst morgen auf dem Testserver komplett sichtbar. Muss leider im Uninetz für die endgültige Umsetzung sein.

**Comment by IngridStoehr** [comment]
Sollte das heute schon funktionieren? Bei mir noch nicht...
