### ISSUE TITLE
Ausklappares Menü: Themenansicht - Reihenfolge

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#36]
Wäre es möglich, die Reihenfolge der Kennzahlen im ausklappbaren Menü aus der Hierarchie zu übernehmen?

**Comment by rockgobo** [comment]
Jupp hab ich bei der einen Datei vergessen mit anzu legen, kann ich aber im
Nachhinein noch tun.

IngridStoehr notifications@github.com schrieb am Mo., 14. Nov. 2016,
10:01:

**Comment by rockgobo** [comment]
Ich habe für die Sekundar, Primarstufe und Erwachsenenbildung die Sortierung aus den Hierachrien übernommen.
