### ISSUE TITLE
Regionenansicht: Aufklappen der Kennzahlen - Berechnung, Datenquelle in einer Zeile

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#37]

**Comment by rockgobo** [comment]
Verstehe nicht ganz was damit gemeint ist, sollen alle Informationen in einer Zeile angezeigt werden? Oder gibt es Fälle, wo diese Begriffe in einer Zeile dargestellt werden? Was der gewünschte Zustand?

**Comment by IngridStoehr** [comment]
[Zeilenabstand.docx](https://github.com/rockgobo/biloatlas/files/692904/Zeilenabstand.docx)

#61 bezieht sich auch hierauf - gewünscht wäre, dass es aussieht wie in dem angehängten Worddokument, dass der Abstand zwischen den "Absätzen" größer ist als zwischen einzelnen Zeilen innerhalb eines Absatzes.
