### ISSUE TITLE
Hauptfarben: Gründ & Lila statt Rot

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#4]
Bitte als zweite Hauptfarbe neben Grün das Lila nutzen (nicht Rot)

**Comment by rockgobo** [comment]
Ist jetzt lila, aber sieht ziemlich heftig aus... Vielleicht doch lieber eine gedecktere Farbe?

**Comment by IngridStoehr** [comment]
Ist doch gut! Kräftig ☺

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. Juni 2016 09:20
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; State change
Betreff: Re: [rockgobo/biloatlas] Hauptfarben: Gründ & Lila statt Rot (#4)

Ist jetzt lila, aber sieht ziemlich heftig aus... Vielleicht doch lieber eine gedecktere Farbe?

**Comment by rockgobo** [comment]
Alles klar, nach dem ersten Schock finde ich es auch ganz ok. Ich frage mich allerdings, wie ihr bei der Printversion die Überschriften setzt. Ich fände ein schönes Grau als Kontrast zur bunten Karte ganz gut.
