### ISSUE TITLE
Startseite: Ausklappbares Menü Regionenansicht - bitte folgende Reihenfolge

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#42]
Stadt Bamberg
Stadt Bayreuth
Stadt Coburg
Stadt Hof
Lkr. Bamberg
Lkr. Bayreuth
Lkr. Coburg
Lkr. Forchheim
Lkr. Hof
Lkr. Kronach
Lkr. Kulmbach
Lkr. Lichtenfels
Lkr. Wunsiedel

**Comment by rockgobo** [comment]
Wirklich nur im Menü? In der Tabelle hatte ich zumindest erst die Regel eingebaut nach der Regionen ID zu sortieren. Ich verstehe, dass es so schöner aus sieht und würde dann versuchen folgende Logik einzubauen:

- zerschneide den Namen
- sortiere alle Namen, die mit städte anfangen nach vorne und sortiere die nach dem Begriff nach dem ersten Leerzeichen
- sortiere den Rest ebenfalls nach dem Wort nach dem ersten Leerzeichen.
- alles andere kommt an das Ende

Alternativ überlege ich noch die Lösung, den Präfix schon in den Daten selbst zu trennen, dann gibt es eine extra Spalte Regionen_typ oder so was ähnliches, dort steht dann entweder Stadt oder Lkr drin....

**Comment by IngridStoehr** [comment]
Im Menü ist es mir aufgefallen. Grundsätzlich sollte diese Reihenfolge überall übernommen werden. Deine Ausführungen zur Umsetzung klingen überzeugend :)

**Comment by rockgobo** [comment]
Vielleicht füge ich doch eine Sortierreihenfolge in die Daten mit ein. Momentan ist es Präfix absteigend und Suffix auf steigend, vielleicht nicht gerade die gängigste Logik :-)

**Comment by IngridStoehr** [comment]
Im Menü stimmt die Reihenfolge nun ja, in der Tabellenansicht (bei Themen) leider noch nicht... hier ist jetzt die Stadt jeweils nach dem entsprechenden Landkreis aufgelistet

**Comment by IngridStoehr** [comment]
In der Tabellenansicht stimmt es immer noch nicht, weiterhin die Stadt jeweils nach dem entsprechenden Landkreis aufgelistet und nicht die 4 Städte zuerst
