### ISSUE TITLE
Diagrammansicht: Überlagerung der Kreisbezeichnungen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#47]
Bitte Abstände bei den Kreisbezeichnungen einfügen - Bsp: Stuktur - Einwohner pro qm

**Comment by rockgobo** [comment]
Ich habe drei Dinge zur Verbesserung unternommen:

- Der äußere Kreis um die "Knickstellen" der Labels zu berechnen wurde erweitert, was bei kleinen Bogenmaßen im oberen Bereich der Kreise für ein wenig mehr Platz sorgt.
- Die Unterüberschriften werden bei ganz kleinen Bogenmaßen nicht mehr angezeigt
- Sollte der Wert der Region gleich null sein wird die Linie und die Labels nicht angezeigt
