### ISSUE TITLE
Daten hochladen: Frühki

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#48]

**Comment by IngridStoehr** [comment]
Z:\00_Austausch\BiLO\BiLO-Atlas\2 - Frühkindliche Bildung

**Comment by rockgobo** [comment]
Nicht erschrecken, hier sind die Daten für Oberfranken zum ersten mal direkt mit drin, diese muss ich erstmal wieder rausfiltern, damit ich sie später anstelle der automatisch berechneten Durchschnitte wieder laden kann.
