### ISSUE TITLE
Ringdiagramm: Anzeige des Durchschnitts - hier Kennzahl nicht Themenbereich anzeigen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#5]
Beim Ringdiagramm wird oben immer der jeweilige Durschnitt angezeigt, bitte hier den Kennzahlnamen nutzen und nicht den Namen des Themenbereichs, es sollten theoretisch auch zwei Kennzahlen aus einem Themenbereich verglichen werden können

**Comment by rockgobo** [comment]
Es wird nun der Name der Kennzahl angezeigt.
