### ISSUE TITLE
Adressen hochladen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#51]
Z:\00_Austausch\BiLO\BiLO-Atlas\Adressen

**Comment by IngridStoehr** [comment]
Johannes bereitet eine Masterdatei zu den Adressen aller Bildungsangebote auf. Er legt sie voraussichtlich nächste im Austauschordner ab.

**Comment by IngridStoehr** [comment]
hier die Daten
[Adressen_Masterliste_Stand Befragung170110.xlsx](https://github.com/rockgobo/biloatlas/files/701711/Adressen_Masterliste_Stand.Befragung170110.xlsx)

**Comment by IngridStoehr** [comment]
Wie versprochen hier die Reihenfolgen für die Legende zur Detailansicht:
## Frühkindliche Bildung
- Krippe
- Kindergarten
- Kinderhaus/Kindertagesstätte
- Großtagespflegestelle
- Sonstige

## Schulbildung
- Grundschule
- Grundschule, Nebenstelle
- [x] [bitte "Grundschule, Nebenstelle" NICHT hochladen]
- Mittelschule
- Mittelschule, Nebenstelle 
- [x] [bitte "Mittelschule geschlossen" und "Mittelschule, Nebenstelle" NICHT hochladen]
- Realschule
- Gymnasium
- Gesamtschule
- Waldorfschule
- Wirtschaftsschule
- Fachoberschule

## Berufliche Bildung
- Berufsfachschule
- Berufsfachschule des Gesundheitswesens

## Studium
- Fachhochschule
- Hochschule
- Universität

## Erwachsenenbildung
- VHS Hauptstellen
- VHS Nebenstellen

**Comment by IngridStoehr** [comment]
Hier die aktualisierte Reihenfolge nach der Spalte C "Art der Einrichtung":

## Frühkindliche Bildung

    Krippe
    Kindergarten
    Kinderhaus/Kindertagesstätte
    Großtagespflegestelle
    Sonstige

## Schulbildung

    Grundschule
    Grundschule, Nebenstelle
    [bitte "Grundschule, Nebenstelle, geschlossen & stillgelegt" NICHT hochladen]
    Mittelschule
    Mittelschule, Nebenstelle
    [bitte "Mittelschule geschlossen" und "Mittelschule, Nebenstelle, stillgelegt" NICHT hochladen]
    Realschule
    Gymnasium
    Gesamtschule
    Waldorfschule
    Wirtschaftsschule
    Fachoberschule

## Berufliche Bildung

    Berufsfachschule
    Berufsfachschule des Gesundheitswesens

## Studium

    Fachhochschule
    Hochschule
    Universität

## Erwachsenenbildung

    VHS Hauptstellen
    VHS Nebenstellen
[alle anderen unter Erwachsenenbildung UND Kulturelle Bildung bitte NICHT hochladen ]

**Comment by IngridStoehr** [comment]
Hinweis: In der Excel sind die Spalten A bis Z korrekt, in den darauffolgenden Spalten könnte sich ein Fehler eingeschlichen haben, allerdings betreffen uns diese nicht, oder?

**Comment by rockgobo** [comment]
Erstmal alle Adressen in die Tabelle [Bilo].[dbo].[Adressen_170125] geladen. Jetzt muss ich noch die Adressen in die alte Struktur übernehmen und die Typen umbauen.

**Comment by IngridStoehr** [comment]
Hier müssen wir nochmal die Farben für die Legende besprechen, des wegen bist Du gestern wohl schon zu uns "getigert" :)

**Comment by rockgobo** [comment]
Moved to #146
