### ISSUE TITLE
OFR-Werte für Schulbildung (Primar- und Sekundarstufe) hochladen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#52]
Z:\00_Austausch\BiLO\BiLO-Atlas\3 - Schulbildung\OFR-Werte_KlassengrößeGS+ÜBQ_161208.xlsx

**Comment by IngridStoehr** [comment]
--> 1. Tabellenblatt

**Comment by rockgobo** [comment]
siehe #54 
die Werte sind glaube ich mittlerweile im Tabellenblatt 3. "OFR_ins" diese habe ich zumindest geladen. Falls das nicht richtig ist das Issue wieder aufmachen und mir kurz das Excel-File erklären.
