### ISSUE TITLE
Werte für Kennzahl: Durchschnittliche Klassengröße an Grundschulen hochladen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#53]
Z:\00_Austausch\BiLO\BiLO-Atlas\3 - Schulbildung\OFR-Werte_KlassengrößeGS+ÜBQ_161208.xlsx

--> 2. Tabellenblatt

**Comment by rockgobo** [comment]
-- Clear old values --

DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE layer_id = '5C8D658E-1857-42EB-B28A-494A7E66E9A9'

DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE layer_id = '4380F99A-FD20-4336-A920-3C7A41482D7C'

DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE layer_id = 'FA3B0A14-A891-45F4-80CB-6E57CDAA7386'

DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE layer_id = '39488A98-1D3D-47EC-9179-CC210AECC94F'
