### ISSUE TITLE
Werte für fehlende Jahre für folgende Kennzahlen: Übertrittsquoten an MS - RS - GYM hochladen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#54]
Z:\00_Austausch\BiLO\BiLO-Atlas\3 - Schulbildung\OFR-Werte_KlassengrößeGS+ÜBQ_161208.xlsx

--> 3. Tabellenblatt

Die OFR-Werte sind bereits in die OFR-Übersicht eingearbeitet. Hier liegen die zugehörigen Werte für die Kreisgebiete.

**Comment by IngridStoehr** [comment]
Jetzt mit im zweiten Tabellenblatt integriert.

**Comment by rockgobo** [comment]
Die versteckten Zeilen 23-64 habe im Datenblatt "OFR_ins" habe ich mal weggelassen, die waren irgendwie nur halb ausgefüllt und unsichtbar. Wurden leider beim Export wieder sichtbar. Was war den mit dieser visuellen "Löschung" beabsichtigt?
