### ISSUE TITLE
Anzeige von 2 Werten bei Kennzahl: Anteil männlich an AbgängerInnen ohne Hauptschulabschluss

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#58]
Bitte ganze Zahl entfernen.

**Comment by rockgobo** [comment]
Nicht verstanden...

**Comment by IngridStoehr** [comment]
Dieses Problem ist mittlerweile gelöst, allerdings stimmen jetzt die Zahlen nicht mehr, der OFR-Durchschnitt liegt bei 84%, auf Kreisebene krebsen die Werte zw. 5 und 15% rum. In der Kartendarstellung ist die Karte zudem in einem Grünton und die Legende geht bis 268%, die Tabellendarstellung funktioniert leider gar nicht...
![anteil mannl oh hs](https://cloud.githubusercontent.com/assets/20164709/21303666/3067ad06-c5c0-11e6-9177-a3be5f03bc68.png)
![anteil mannl oh hs_tab](https://cloud.githubusercontent.com/assets/20164709/21303686/53fd0df6-c5c0-11e6-9a15-2509cb1dfe8c.png)

**Comment by rockgobo** [comment]
Das hat sich erledigt, war ein Artefakt durch den Versuch die Zahlen mit einem Komma anstelle eines Punktes darzustellen.
