### ISSUE TITLE
Ausklappbare Menüs - Themenbereichsauswahl ergänzen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#6]
Um in der Themenansicht die ausgewählten Kennzahlen zu ändern, müsste es bei der ersten Kennzahl auch das ausklappbare Menü zu den Themenbereichen geben (wie bei der zweiten Kennzahl…);

**Comment by rockgobo** [comment]
Themenauswahl ist nun wieder drin
