### ISSUE TITLE
Übernahme der Auswahl des Themengebiets auf der Startseite in ausklappbares Menü

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#60]
Bisher wird - auch wenn ich auf der Startseite z.B. Schulbildung auswähle - dann in der Themenansicht im ausklappbaren Menü "Strukturelle Rahmenbedingungen" angezeigt.

**Comment by rockgobo** [comment]
Die Auswahl der Themenauswahl in der Seite versucht nun die Routeninformationen aus der URL als Auswahl zu übernehmen, anstelle des ersten Themas, wie seither. 
Das heißt es kann nun direkt in die Themen von der Startseite aus gesprungen werden.
