### ISSUE TITLE
Bitte Zeilenabstand im Text (=Text bei Berechnung) enger als zw. Absätzen (=zw. Jahr, Quelle, Berechnung...)

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#61]
![zeilenabstand](https://cloud.githubusercontent.com/assets/20164709/21005935/224a099e-bd37-11e6-9cf3-559cb917f0ff.png)

**Comment by rockgobo** [comment]
Dann wird das neue Label "Eigene Berechnung" umbrechen und sieht dann auch nicht sehr schön aus.

**Comment by IngridStoehr** [comment]
zusätzlich: Eigene Berechnung etc. nicht einblenden, wenn das Feld leer ist
