### ISSUE TITLE
Regionenansicht: Bezeichnung der Kennzahl parallel zu y-Achse (nicht unter x-Achse)

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#64]

**Comment by rockgobo** [comment]
Kann man machen, bei den vielen Texten ist das Label aber viel zu lang. Was ist der Mehrwert von der Beschreibung der Kennzahl als Achsenbeschriftung?

**Comment by IngridStoehr** [comment]
Richtig ist, dass die Kennzahlbeschriftung die y-Achse betrifft, der Rest ist m.E. Geschmackssache. Ich habe mich da gefügt.

**Comment by rockgobo** [comment]
#80 wird dort fortgesetzt
