### ISSUE TITLE
Bitte als Dezimaltrennzeichen Komma statt Punkt verwenden

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#66]

**Comment by rockgobo** [comment]
Also diese Anforderung ist ziemlich kniffelig. Das Komma müsste man rein für die Darstellung einfügen. Ich habe versucht das zentral zu machen, aber dann interepretiert der Browser alle Zahlen als tausender und rechnet entsprechend, was zum Totalzusammenfall der Oberfläche führt. Ansonsten kann ich auch überall, wo Zahlen auftauchen aus einem Punkt ein Komma machen, was ein ziemlicher Aufwand ist und wir Gefahr laufen, es an irgendeiner Stelle zu vergessen. Ich werde mal noch ein wenig drüber nachdenken, aber wenn das nicht unbedingt nötig ist würde ich gerne darauf verzichten.

**Comment by IngridStoehr** [comment]
Ich habe gerade nochmal mit Michaela darüber gesprochen und demnach wäre es schon sehr wünschenswert, wenn es klappt. Argument ist, dass es seltsam ist, eine deutschsprachige Website zu veröffentlichen und bei den Zahlen die amerikanische Schreibweise zu nutzen.

**Comment by rockgobo** [comment]
Heureka, nachdem ich verstanden habe, das es ja eine Standard-Anforderung ist und ich mir konzeptionell überlegt habe, wie man es am besten angeht, habe ich herausgefunden, das es genau so im Framework schon implementiert ist. An einigen Stellen muss ich zwar noch selbst Hand anlegen, aber die meisten Stellen sind recht einfach zu konfigurieren.
ngLocale ist das Zauberwort und der Filter "number : 1" Ich werde das so an den einfachen Stellen mal einbauen und dann hochladen.

**Comment by IngridStoehr** [comment]
in der Regionenansicht noch nicht umgesetzt

**Comment by rockgobo** [comment]
Jetzt auch im Colorpicker. Müsste die letzte Stelle gewesen sein. Tritt es wieder auf entweder den Filter numberUnit : _unit_ verwenden oder im Code $filter('numberUnit')(_value_, _unit_)

**Comment by rockgobo** [comment]
In den Diagrammen der Regionenansicht werden nun die Tooltips selbst erstellt, dadurch konnte man dort die Zahlen ebenfalls lokalisieren. 
Die Values bei den Barcharts wurden noch im Standarformat angezeigt, hier wird allerdings nicht das tickFormat verwendet und musste daher entfernt werden.
