### ISSUE TITLE
Reihenfolge Themen - Studium aktuell an erster nicht an vorletzter Stelle

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#67]
![themen-reihenfolge_studium](https://cloud.githubusercontent.com/assets/20164709/21132343/b859a50e-c113-11e6-97bd-5c842154dbbb.png)

**Comment by rockgobo** [comment]
Kann ich nicht bestätigen. Kannst du das nochmal nachschauen?
