### ISSUE TITLE
Ausklappbare Menüs - Themenbereichsauswahl bereits Gewählten als Option bei 2. Kennzahl ergänzen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#7]
Aktuell steht bei der Themenansicht bei der Auswahl der zweiten Kennzahl der Bereich „strukturelle Rahmendaten“ als Option nicht zur Verfügung

**Comment by rockgobo** [comment]
Habe die Restriktion entfernt
