### ISSUE TITLE
Schulbildung (Sekundarstufe): Berichtigung von Werten einzelner Kennzahlen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#70]
Die Vorlage mit den berichtigten Werten für die betreffenden Kennzahlen liegt hier: (Ich habe versucht, sie nach der Vorlage aufzubereiten, die Du Eva gezeigt hast)
Z:\00_Austausch\BiLO\BiLO-Atlas\3 - Schulbildung\Daten-Sek_Online_161214_Abgäng-Absolv_berichtigt.xlsx

**Comment by IngridStoehr** [comment]
und ich habe gerade (11:42, 14.12.) noch die berichtigten Jahreszahlen ergänzt, denn bei allen Kennzahlen zu den AbgängerInnen und AbsolventInnen darf nicht der erste Teil des Schuljahres, sondern muss der letzte Teil des Schuljahres angezeigt werden. Ich den berichtigten Werte habe ich das nun gemacht, kannst Du das für die anderen Kennzahlen zu AbsolvenInnnen und AbgängerInnen an anderer Stelle übernehmen?

**Comment by rockgobo** [comment]
Das heißt man muss das Jahr um eins nach oben zählen?

**Comment by IngridStoehr** [comment]
Ja, aber nur bei den Kennzahlen zu den AbsolventInnen und AbgängerInnen.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. Dezember 2016 12:06
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Schulbildung (Sekundarstufe): Berichtigung von Werten einzelner Kennzahlen (#70)


Das heißt man muss das Jahr um eins nach oben zählen?

**Comment by rockgobo** [comment]
begin transaction

UPDATE v
  SET v.Value = d.Wert
  FROM [Bilo].[dbo].[Values_Sek_Onl_GS-Sek_weibl_Absolv_170201] as d
  join atlas.[Values] as  v on v.Layer_id = d.layer_id AND v.Region_id = d.[Region (ID)] AND v.Year = d.Jahr

commit

**Comment by rockgobo** [comment]
Ich habe jetzt nur das zweite Datenblatt verwendet um die Daten zu korrigieren. Was ist mit dem ersten Datenblatt, da steht was von neuen Daten. Soll ich damit auch was machen?

**Comment by IngridStoehr** [comment]
Ja, bitte das erste DAtenblatt auch verwenden, hier gibt es neue Kennzahlen. Hast Du die Excel vom Austauschordner genommen? Die hier in github angehängte war ja schon älter....

**Comment by rockgobo** [comment]
Ich nehme nur noch Dokumente vom Server, also dem Austausch Ordner meine
ich.

IngridStoehr <notifications@github.com> schrieb am Fr., 3. Feb. 2017, 11:20:

Ja, bitte das erste DAtenblatt auch verwenden, hier gibt es neue
Kennzahlen. Hast Du die Excel vom Austauschordner genommen? Die hier in
github angehängte war ja schon älter....

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/rockgobo/biloatlas/issues/70#issuecomment-277213048>,
or mute the thread

**Comment by rockgobo** [comment]
Die ganzen Daten aus dem Excel-File sind jetzt in der Datenbank und die bestehenden wurden verbessert. Wenn jetzt noch die Duplikate entfernt werden, sind wir mit den Daten glaube ich erstmal fertig.

**Comment by IngridStoehr** [comment]
Hallo Christian,

Danke!
Ist das eine Aufgabe für mich, die Duplikate zu entfernen?
Für Dich zur Info: Ich bin kurzfristig morgen und übermorgen (7.+8.2.) auf einer externen Weiterbildung, also nicht im Haus und auch nicht per mail erreichbar. Heute bin ich noch bis 12 Uhr da, sollten wir uns nochmals treffen oder sind die offenen issues soweit klar? Die Adressdaten liegen nun auch aktualisiert vor, ich lege sie in den Austauschordner und passe das issue an.

Herzlich
Ingrid


Von: rockgobo [mailto:notifications@github.com]
Gesendet: Freitag, 3. Februar 2017 16:20
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Schulbildung (Sekundarstufe): Berichtigung von Werten einzelner Kennzahlen (#70)


Die ganzen Daten aus dem Excel-File sind jetzt in der Datenbank und die bestehenden wurden verbessert. Wenn jetzt noch die Duplikate entfernt werden, sind wir mit den Daten glaube ich erstmal fertig.
