### ISSUE TITLE
Bitte Spieldaten für Frühkindliche Bildung löschen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#72]

**Comment by rockgobo** [comment]
BEGIN TRANSACTION
DECLARE @old_layers TABLE (Value uniqueidentifier)
  insert into @old_layers Values   ('73417BD1-32EF-4642-897F-EC4C7E9667F9')
  insert into @old_layers Values   ('32683F06-CE48-4357-B52E-EB2605F6054F')
  insert into @old_layers Values   ('CF56794F-93AB-4E7A-839C-ACE96A60D199')
  insert into @old_layers Values   ('58BA1460-A1BD-4EDE-B416-460D32C6420C')
  insert into @old_layers Values   ('957636F8-1E94-42A5-AE12-07F724A379E9')

DELETE FROM atlas.[Values] 
  WHERE Layer_id IN (SELECT Value FROM @old_layers)

DELETE FROM [Bilo].[atlas].[Layers]
  WHERE Id IN (SELECT Value FROM @old_layers)

-----
Auf Testdatenbank ausführen

**Comment by IngridStoehr** [comment]
Soll ich da irgendwas machen? Bei mir sind die Daten noch da...

**Comment by rockgobo** [comment]
Jetzt habe ich das Skript ausgeführt :-)
