### ISSUE TITLE
Struktur: Bevölkerungsprognose

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#75]
Bitte hier die Zahlen für die Jahre 2014 und 2015 entfernen.

**Comment by IngridStoehr** [comment]
Gleiches gilt für Prognose des Jugendquotienten und Prognose des Altenquotienten

**Comment by rockgobo** [comment]
DB_Bilo_FULL_20170104_053411.bak vor Löschung

**Comment by rockgobo** [comment]
DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE Layer_id = '3808ECC6-A548-410E-9920-3C9FF0050C01'
  AND (Year = 2015 OR Year = 2014)

DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE Layer_id = 'C985CC6A-157A-4CD9-AF58-B211C6133211'
  AND (Year = 2015 OR Year = 2014)

DELETE
  FROM [Bilo].[atlas].[Values]
  WHERE Layer_id = '6D3928D8-988E-4678-B9EF-686FF50A6721'
  AND (Year = 2015 OR Year = 2014)
