### ISSUE TITLE
OFR-Werte Struktur, Aktualisierung Strukturdaten und 2 neue Kennzahlen in Struktur

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#76]
Für die Strukturellen Rahmendaten liegen 3 Bearbeitungsfälle vor:
1. Bereits eingespielte Daten müssen aktualisiert werden, d.h. die 2015er Daten für alle Kreise und OFR und OFR-Werte für alle vergangenen Jahre (1. Tabellenblatt)
2. Bereits eingespielte Daten müssen berichtigt werden, dies betrifft Bruttoinlandsprodukt (BIP) pro Kopf und Einkommen der privaten Haushalte pro Kopf (2. Tabellenblatt)
3. Bitte zwei neue Kennzahlen direkt unter "Wirtschaft" (vor Jugendarbeitslosenquote) einrichten: Arbeitslosenquote Männer & Arbeitslosenquote Frauen (3. Tabellenblatt)
Die Daten dazu liegen hier:
Z:\00_Austausch\BiLO\BiLO-Atlas\1 - Strukturelle Rahmendaten_online\Aktualisierungen

**Comment by IngridStoehr** [comment]
Und bitte noch zwei neue Kennzahlen einrichten: Unter soziale Lage anschließend an die bisherigen
1) SGB II-Quote
2) Kinder mit Bezug von Sozialgeld
Die Daten dazu liegen ebenfalls in obiger Datei im 3. Tabellenblatt

**Comment by rockgobo** [comment]
Kann ich der Einfachkeitshalber auch alle Strukturdaten wegwerfen und die Daten komplett aus diesen 4 Tabellenblätter neu aufbauen? Ich glaube wir sollten da nochmal drüber reden.

**Comment by rockgobo** [comment]
Das dritte Datenblatt "Neue Kennzahlen" hat bei mir vier unterschiedliche Kennzahlen, soll ich die Arbeitslosenquoten für Männer und Frauen weglassen oder lieber die "Tabelle 1" verwenden?

**Comment by rockgobo** [comment]
Habe die SGB II-Quote und Kinder mit Bezug aus der Tabelle 1 übernommen, da es nach oberflächlicher Betrachtung eh dieselben Daten sind, sind in die Datenbank übernommen worden.

**Comment by rockgobo** [comment]
Ok das laden ist vorbereitet, kleine Analyse vor dem Laden:
- Aktualisierungen: 
     737 insgesamt, 
     711 sind komplett neu
     26 Werte existieren bereits, 13 davon haben neue Werte

- Berichtigungen:
     260 insgesamt
     260 Werte existieren bereits, 260 davon haben auch neue Werte

**Comment by rockgobo** [comment]
Daten wurden mit Hilfe des MERGE Befehls von SQL integriert.

**Comment by rockgobo** [comment]
begin transaction

MERGE INTO [atlas].[Values] VALUES_OLD

USING (SELECT [Region]
      ,[Region (ID)]
      ,[Jahr]
      ,[Thema]
      ,Round(cast(replace([Wert],',','.') as float),1)  As value,
      [layer_id]
	  FROM [dbo].[Struktur_Aktualisierung_161222]) VALUES_NEW
	ON VALUES_NEW.jahr = VALUES_OLD.Year AND cast(VALUES_NEW.layer_id as uniqueidentifier) = VALUES_OLD.Layer_id AND VALUES_OLD.Region_id = VALUES_NEW.[Region (ID)]
WHEN MATCHED THEN
   UPDATE 
      SET VALUES_OLD.value = VALUES_NEW.value
WHEN NOT MATCHED THEN
	INSERT ([Region_id],[Layer_id],[Value],[Year])
	VALUES (VALUES_NEW.[Region (ID)],VALUES_NEW.[layer_id],VALUES_NEW.value,VALUES_NEW.[Jahr]);

commit transaction

**Comment by IngridStoehr** [comment]
Bitte die neuen Kennzahlen Arbeitslosenquote für Männer und Frauen auch mit aufnehmen. Danke. „Tabelle 1“ war eine Hilfstabelle und hätte gelöscht werden müssen, die Werte daraus stehen in „neue Kennzahlen“.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. Januar 2017 10:25
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] OFR-Werte Struktur, Aktualisierung Strukturdaten und 2 neue Kennzahlen in Struktur (#76)


Das dritte Datenblatt "Neue Kennzahlen" hat bei mir vier unterschiedliche Kennzahlen, soll ich die Arbeitslosenquoten für Männer und Frauen weglassen oder lieber die "Tabelle 1" verwenden?

**Comment by IngridStoehr** [comment]
ich kann das issue nicht wieder öffnen...

**Comment by rockgobo** [comment]
Musst du das wieder öffnen?

**Comment by IngridStoehr** [comment]
Nicht zwingend, nur dürfen wir nicht vergessen, dass die beiden neuen Kennzahlen hochgeladen werden…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Montag, 9. Januar 2017 09:06
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] OFR-Werte Struktur, Aktualisierung Strukturdaten und 2 neue Kennzahlen in Struktur (#76)


Musst du das wieder öffnen?

**Comment by rockgobo** [comment]
Ich glaube die habe mithilfe von Tabelle 1 schon hochgeladen.

**Comment by IngridStoehr** [comment]
In Tabelle 1 stehen nur die beiden neuen Kennzahlen Sozialgeld und SBGII Quote, nicht aber Arbeitslosigkeit Männer und Frauen;  Erstere sind hochgeladen und werden in der Regionenansicht (an erster Stelle, hier bitte noch die richtige Reihenfolge unter soziale Lage beachten) angezeigt, NICHT aber im ausklappbaren Menü unter der Themenansicht…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Montag, 9. Januar 2017 09:18
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] OFR-Werte Struktur, Aktualisierung Strukturdaten und 2 neue Kennzahlen in Struktur (#76)


Ich glaube die habe mithilfe von Tabelle 1 schon hochgeladen.

**Comment by IngridStoehr** [comment]
Ich habe mir mal die Werte zu Altenquotient angeguckt, hier stehen leider für OFR noch die alten Werte drin und nicht die neuen richtigen aus der Exceltabelle 
Z:\00_Austausch\BiLO\BiLO-Atlas\1 - Strukturelle Rahmendaten_online\AktualisierungenKennzahlen_Struktur_Aktualisierung_05012017.xlsx

Beispiel Jahr 2015 müsste heißen für OFR: 36,1 heißt aber 37,1; für 2014 müsste heißen 35,8, heißt aber 36,8...

**Comment by IngridStoehr** [comment]
Das geht leider nicht, da in diesen aufbereiteten Tabellen leider nicht alle Kennzahlen für alle Jahre enthalten sind…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. Januar 2017 11:40
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] OFR-Werte Struktur, Aktualisierung Strukturdaten und 2 neue Kennzahlen in Struktur (#76)


Kann ich der Einfachkeitshalber auch alle Strukturdaten wegwerfen und die Daten komplett aus diesen 4 Tabellenblätter neu aufbauen? Ich glaube wir sollten da nochmal drüber reden.

**Comment by rockgobo** [comment]
OF-Werte werden überall noch berechnet und nicht aus der Datenbank gelesen. Daher sind sie überall noch richtig :-D 
Ich muss dafür die Logik der Software ändern, kommt noch. Das gibt ein neues Issue (siehe #79)

**Comment by rockgobo** [comment]
Ich habe die beiden Kennzahlen "Kinder mit Bezug von Sozialgeld" und "SBGII Quote" unter "Soziale Lage" gehängt. 
Die "Arbeitslosen Männer / Frauen" sind nun unter "Wirtschaft" zu finden.
