### ISSUE TITLE
Regionenübersicht: Kein Liniendiagramm bei Zeitpunkten 

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#8]
Wenn nur die Daten für 3 Jahre vorliegen, bitte KEIN Liniendiagramm, sondern Balkendiagramm nutzen – je Jahr zwei Balken (Lkr. & Ofr.)

**Comment by rockgobo** [comment]
Wunderschöne Balkendiagramme werden jetzt passend in den Standardfarben angezeigt. 
Grün - Oberfranken
Lila - Region
