### ISSUE TITLE
Regionenansicht: zweizeilige Tabellenbeschriftung bei zu langen Namen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#80]

**Comment by rockgobo** [comment]
Habe als ersten Workaround die Höhe der Diagramme an die Länge der Bezeichner angepasst (Mindesthöhe 250). Mehrzeilige Texte sind in NVD3 nicht vorgesehen und können nicht konfiguriert werden. Dieses Verhalten müsste erst programmiert werden. Ich denke es sieht auch erst mal in ordentlich aus.
