### ISSUE TITLE
Keine Oberfrankendaten in "Berufliche Bildung"

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/biloatlas#87]
Die Daten für "Berufliche Bildung" sind doch in der Datei "Master Ausbildung_201216" zu finden? Dort fehlen die Oberfrankenwerte.

**Comment by IngridStoehr** [comment]
Hier ist eine neue Masterdatei nochmals mit allen Werten für Berufliche Bildung inkl. OFR und neuer Kennzahlen.
Im ersten Tabellensheet ist eine Übersicht zur "alten" Hierarchie und zur "neuen" Hierarchie. Das zeigt, dass enige Kennzahlen gelöscht werden müssten und dafür ein paar neu hinzukommen. 
Im zweiten Sheet folgen die Daten mit allen Werten (Kreise & OFR) für die "bleibenden" Kennzahlen inkl. layer id.
Im dritten Sheet folgen die Daten mit allen Werte (Kreise & OFR) für die "neuen" Kennzahlen, hier gibt es logischerweise noch keine layer id.
Die neuen Formulierungen sind im webAtlas auch schon umgesetzt.
[Master Ausbildung NEU_170126.xlsx](https://github.com/rockgobo/biloatlas/files/731830/Master.Ausbildung.NEU_170126.xlsx)

**Comment by IngridStoehr** [comment]
Die Datei liegt auch im Austauschordner.

**Comment by rockgobo** [comment]
Die Datei kann ich so nicht laden:

- Die Spalten Value beinhaltet sowohl Ganzzahlen als auch Prozentzahlen (allerdings als Excel-Prozent formatiert), wenn die komplett umstelle, habe ich eine Mischung aus Zahlen wie 0,314023832 (für 31%) und Zahlen wie 10023,0 für 10023 
- Bei Blätter sind über einen Filter über die Themenbereiche gebaut, wenn ich aus diesen Blättern ein CSV machen, habe ich wieder ALLE Daten aus dem Tabellenblatt, auch die versteckten. 
- Bei den neuen Daten sind ziemlich viele Fehler drin (#DIV/0! - irgendwas durch Null geteilt), ist dann dann 0?
- Viele Felder sind leer, sind das dann Missings oder 0?

**Comment by IngridStoehr** [comment]
Sorry.
Zu Punkt 1: Das habe ich nun angepasst, die Prozentzahlen sind nun Zahlen wie 31,4 für 31,4 Prozent
Zu Punkt 2: Der Filter diente der Aufbereitung, alle Werte / Zeilen sind relevant. Ich habe diese nun anzeigen lassen.
Zu Punkt 3 & 4: Die Fehler sind raus – was 0 bzw. Missings betrifft, habe ich nun mit Michaela gesprochen, ich schreibe dazu ein neues issue und dann könnten wir noch drüber sprechen…

Wie sieht Dein Zeitplan aus? Ist letzte Woche was dazwischen gekommen, oder?
LG
Ingrid

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 26. Januar 2017 15:45
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


Die Datei kann ich so nicht laden:

  *   Die Spalten Value beinhaltet sowohl Ganzzahlen als auch Prozentzahlen (allerdings als Excel-Prozent formatiert), wenn die komplett umstelle, habe ich eine Mischung aus Zahlen wie 0,314023832 (für 31%) und Zahlen wie 10023,0 für 10023
  *   Bei Blätter sind über einen Filter über die Themenbereiche gebaut, wenn ich aus diesen Blättern ein CSV machen, habe ich wieder ALLE Daten aus dem Tabellenblatt, auch die versteckten.
  *   Bei den neuen Daten sind ziemlich viele Fehler drin (#DIV/0! - irgendwas durch Null geteilt), ist dann dann 0?
  *   Viele Felder sind leer, sind das dann Missings oder 0?

**Comment by IngridStoehr** [comment]
Ergänzung: Die Daten liegen im Austauschordner mit heutigem Datum unter Ausbildung.

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Donnerstag, 26. Januar 2017 15:45
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


Die Datei kann ich so nicht laden:

  *   Die Spalten Value beinhaltet sowohl Ganzzahlen als auch Prozentzahlen (allerdings als Excel-Prozent formatiert), wenn die komplett umstelle, habe ich eine Mischung aus Zahlen wie 0,314023832 (für 31%) und Zahlen wie 10023,0 für 10023
  *   Bei Blätter sind über einen Filter über die Themenbereiche gebaut, wenn ich aus diesen Blättern ein CSV machen, habe ich wieder ALLE Daten aus dem Tabellenblatt, auch die versteckten.
  *   Bei den neuen Daten sind ziemlich viele Fehler drin (#DIV/0! - irgendwas durch Null geteilt), ist dann dann 0?
  *   Viele Felder sind leer, sind das dann Missings oder 0?

**Comment by rockgobo** [comment]
In der Masterdatei ist noch eine kleine Unstimmigkeit: Heißt es "Neueintritte im SBS - Anzahl" oder "Neueintritte in SBS - Anzahl", das gleiche gibt es auch für ÜS... momentan matchen diese in der Exceldatei nicht.
Wenn ich den Match noch hinbekomme kann ich das morgen (Dienstag laden). Also die Ausnahme ist gerade eher, dass ich genug Ruhe habe um vernünftig weiter zu kommen. Wenn bis Mittwoch nichts voran geht werde ich mich nach zu Hause zurückziehen.

**Comment by rockgobo** [comment]
HUIHUIHIUIII...
Zum Glück hab ich vor dem Laden noch eine Kontrolle auf Duplikate gemacht. Bei den neuen Daten gab es unglaublich viele doppelte Werte. Ich habe herausgefunden woran es liegt, die Region_ids sind alle falsch 
22928 wurde zum Beispiel für Bamberg, Bayreuth und Coburg verwendet. Ich werde das gleich noch reparieren und dann sind es hoffentlich keine Duplikate mehr.

**Comment by IngridStoehr** [comment]
Super!
Die Frage gestern zu „in SBS“ oder „im SBS“ war im Spam ordner, sorry, bitte „im SBS“

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 12:11
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


HUIHUIHIUIII...
Zum Glück hab ich vor dem Laden noch eine Kontrolle auf Duplikate gemacht. Bei den neuen Daten gab es unglaublich viele doppelte Werte. Ich habe herausgefunden woran es liegt, die Region_ids sind alle falsch
22928 wurde zum Beispiel für Bamberg, Bayreuth und Coburg verwendet. Ich werde das gleich noch reparieren und dann sind es hoffentlich keine Duplikate mehr.

**Comment by rockgobo** [comment]
Also ein Duplikat gibt es noch: 
Ist "SuS im ÜS - Anzahl"	in "Stadt Coburg"	im Jahr "2013"
**154** oder **164**?

**Comment by rockgobo** [comment]
Ich nehme jetzt vorerst 154, falls das falsch ist kann man das später noch verbessern.

**Comment by IngridStoehr** [comment]
154 ist richtig!

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 13:01
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


Ich nehme jetzt vorerst 154, falls das falsch ist kann man das später noch verbessern.

**Comment by rockgobo** [comment]
So alles geladen und es gibt nun auch Oberfrankendaten. Was ich leider getan habe: Es wurden beim Laden der Kennzahlen alle Beschreibungstexte und Einheiten mit gelöscht... habt ihr die noch irgendwo, dann spiele ich sie ein, ansonsten steht der Adminbereich für diese Daten ja bereit.

**Comment by IngridStoehr** [comment]
Danke, dass die Daten hochgeladen sind!
Für den Rest würden wir Dir tatsächlich eine Excel vorbereiten zum Hochladen, da es mit der Maske bei so vielen Sachen sehr mühsam ist (und der Frustrationsgrad sonst zu hoch werden könnte, da alles ja schon angepasst wurde….)…


Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Januar 2017 13:28
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


So alles geladen und es gibt nun auch Oberfrankendaten. Was ich leider getan habe: Es wurden beim Laden der Kennzahlen alle Beschreibungstexte und Einheiten mit gelöscht... habt ihr die noch irgendwo, dann spiele ich sie ein, ansonsten steht der Adminbereich für diese Daten ja bereit.

**Comment by rockgobo** [comment]
Ich werde gleich noch schauen, was in meiner lokalen Datenbank ist oder ob es Backups gibt. Dann musst ihr nicht alles nochmal suchen.

**Comment by IngridStoehr** [comment]
Alles klar, dann warten wir mit der „Auftragsvergabe“ noch…

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 1. Februar 2017 08:30
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


Ich werde gleich noch schauen, was in meiner lokalen Datenbank ist oder ob es Backups gibt. Dann musst ihr nicht alles nochmal suchen.

**Comment by IngridStoehr** [comment]
Treffen wir uns kurz, wenn Du kommst?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Mittwoch, 1. Februar 2017 08:30
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Comment
Betreff: Re: [rockgobo/biloatlas] Keine Oberfrankendaten in "Berufliche Bildung" (#87)


Ich werde gleich noch schauen, was in meiner lokalen Datenbank ist oder ob es Backups gibt. Dann musst ihr nicht alles nochmal suchen.

**Comment by rockgobo** [comment]
Die "Auftragsvergabe" ist überflüssig habe alles aus dem Backup übernommen. Hast du hoffentlich schon bemerkt :-~
