### ISSUE TITLE
Regionenansicht: Nutzerhinweis zu "Detailansicht" ergänzen

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#93]
Folgender Text als Erläuterung zur "Detailansicht" wäre denkbar:

In der Detailansicht finden Sie die Adressinformationen zu den Einrichtungen des Kreisgebiets nach verschiedenen Bildungsbereichen.

**Comment by rockgobo** [comment]
Text hinzugefügt
