### ISSUE TITLE
Regionenansicht: Auf Anzeige der Wappensammlung (unter Karte) wird verzichtet

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#95]
Nicht das einzelne zum Kreisgebiet zugehörige Wappen (rechts oben)

**Comment by rockgobo** [comment]
Die Wappen wurden entfernt. Bin noch nicht so ganz schlüssig, wo man die Knöpfe für die Detailansicht und das herunterladbare PDF hintun soll. Aber diese haben jetzt zumindest schicke Icons. Wenn dir was einfällt schreib einfach einen neuen Issue.

**Comment by IngridStoehr** [comment]
Die Icons finde ich auch ganz wunderbar! Danke!
Was die Platzierung betrifft, so fand ich die Stelle unter der Übersichtskarte mit den Einrichtungen ganz gut, da sich hierauf ja auch die Detailansicht bezieht und links würden dann die Themenbereiche wieder hochrutschen.
Mir ist aufgefallen, dass wir in den Text wohl noch hineinpacken müssten, dass es sich beim Kreisprofil um jenes aus dem Print-Atlas handelt… Vielleicht so:
In der Detailansicht finden Sie die Adressinformationen zu den Einrichtungen des Kreisgebiets nach verschiedenen Bildungsbereichen.
Das Kreisprofil stammt aus dem Atlas BildungsLandschaft Oberfranken (PDF-Version) und beinhaltet einzelne aufbereitete Kennzahlen je Themenbereich.

Zu lang und umständlich?

Von: rockgobo [mailto:notifications@github.com]
Gesendet: Dienstag, 24. Januar 2017 16:04
An: rockgobo/biloatlas
Cc: Stöhr, Ingrid; Author
Betreff: Re: [rockgobo/biloatlas] Regionenansicht: Auf Anzeige der Wappensammlung (unter Karte) wird verzichtet (#95)


Die Wappen wurden entfernt. Bin noch nicht so ganz schlüssig, wo man die Knöpfe für die Detailansicht und das herunterladbare PDF hintun soll. Aber diese haben jetzt zumindest schicke Icons. Wenn dir was einfällt schreib einfach einen neuen Issue.

**Comment by rockgobo** [comment]
Ich habe nun bei der Sortierung die Überkategorien mit eingerechnet, nun fängt es mit 'Bevölkerungszahl' an. Ist das so richtig?
