### ISSUE TITLE
Themenansicht: Karten und Ringdiagramm - Festlegung der Kategorienanzahl

### ISSUE THREAD

**Issue by IngridStoehr** [rockgobo/biloatlas#96]
Wäre es möglich die flexible Auswahl der Anzahl der dargestellten Kategorien wieder aufzunehmen?
D.h., der Nutzer kann wählen, ober er die aktuell neun verschiedenen Kategorien haben will oder doch nur 5...

**Comment by IngridStoehr** [comment]
hier nun der abgestimmte Bedarf: 
Bitte eine Möglichkeit anbieten, bei der der Nutzer die Anzahl der Kategorien beliebig festlegen kann. 
Danke!

**Comment by rockgobo** [comment]
Ein Icon einbauen über das man die Anzahl der Kategorien ändern kann als visuelle Unterstützung für den Nutzer.

**Comment by IngridStoehr** [comment]
Bisher kann zwischen 3, 5 oder 9 Kategorien ausgewählt werden. Der Wunsch wäre gewesen, dass der Nutzer die Kategorienanzahl beliebig festlegen kann... (<10).

**Comment by rockgobo** [comment]
Das ist eine heiße Annahme, das der Nutzer das wirklich braucht. Habt ihr euch schon mal überlegt, den Atlas hier im Haus zu streuen und wir bauen noch ein paar Logs mit ein mit denen wir die Nutzung des Atlas messen können?

**Comment by IngridStoehr** [comment]
Ich glaube, es ging darum, dass nicht wir (normativ) festlegen, wo die Grenzen der Kategorien sind, sondern der Nutzer die Standardeinstellung und damit die (ggf. positive oder negative) Einfärbung ändern kann...

**Comment by IngridStoehr** [comment]
Vorab: Eine Möglichkeit zum Ausblenden wäre gut, bisher man auf "Abbrechen" gehen, um den Kasten wieder loszuwerden...

Bei Firefox funktioniert alles wie bei Dir unten.

Beim IE (11) funktioniert leider nix, nichtmal die Auswahl der Kennzahlen  - siehe: 
![ie 11](https://cloud.githubusercontent.com/assets/20164709/23356513/6e70f566-fcda-11e6-8f4e-a891abd57929.jpg)

**Comment by rockgobo** [comment]
Wieder war gelernt, der IE mag keine default parameter und er kennt Object.assign nicht. Beide wurden mit Polyfill nachgeschult und die HTML5 Fähigkeiten des Browsers mit HTMLShiv ausgeglichen.
